### ISSUE TITLE
Clarification of --search BEST

### ISSUE THREAD

**Issue by protist** [stephaneguindon/phyml#102]
In the latest release of PhyML, I can see in the help

    $ phyml --help
    ...
    -s (or --search) move
        Tree topology search operation option.
        Can be either NNI (default, fast) or SPR (a bit slower than NNI)
        or BEST (best of NNI and SPR search).

I tried `BEST`, but got a warning.

    $ phyml -i input.phy -s BEST
    ...
    . The BEST option is deprecated. PhyML now uses a mix of SPRs and NNIs.
    ...
    . Tree topology search:				 Best of NNIs and SPRs

I was confused, because despite the warning, specifying this option apparently altered the parameters reported by phyml. Is `BEST` still active? I also note that the default is still `NNIs`, so I was unsure what the warning meant by "PhyML *now* uses". I also note that [this page](http://www.atgc-montpellier.fr/phyml/benchmarks/index.php?ben=md) still refers to `BEST`.

    $ phyml-mpi --version
    ...
    . This is PhyML version 3.3.20190321.

**Comment by protist** [comment]
Erm, why was this closed? I'm still getting the same result with version 3.3.20200621.

**Comment by stephaneguindon** [comment]
The BEST option should not impact the analysis. Because PhyML relies on a bit of randomness in the tree searching algorithm, one may obtain distinct results across different runs, e.g., one with the BEST option and another without. Does that match your observations?

**Comment by protist** [comment]
Thanks @stephaneguindon. I haven't tested the various permutations specifically, and I had thought that there would be some random noise based on the data input anyway. Either way, I found the documentation confusing and somewhat contradictory. `--help` suggests that it's useful, but when using `BEST`, the warning suggests otherwise. Also, there's the confusion (to me) with the reference to the "mix of SPRs and NNIs".

**Comment by stephaneguindon** [comment]
I've just amended the help section to indicate that the BEST option is now deprecated.

**Comment by protist** [comment]
Thanks @stephaneguindon !
