### ISSUE TITLE
using phyml in pipeline mode

### ISSUE THREAD

**Issue by annahake** [stephaneguindon/phyml#105]
Hi Stephane, 
is there a "quiet" option for phyml? 
More precisely, is there a way to avoid the following prompt by using command line options?

> Do you really want to proceed? [Y/n] 

Best, 
Anna

**Comment by stephaneguindon** [comment]
Hi Anna,
Sorry I missed your post... The '--quiet' option is what you're looking for.
Regards,
-Stephane-

**Comment by annahake** [comment]
Thank you, Stephane. 
I only checked the options on this [website](http://www.atgc-montpellier.fr/phyml/usersguide.php?type=command).
