### ISSUE TITLE
Output file (directory) option

### ISSUE THREAD

**Issue by annahake** [stephaneguindon/phyml#107]
Hi Stephane, 
is there an option to set the output directory or the output file name?
As far as I understood it, phyml creates the files in the same directory as the input file by adding suffixes to the input file name. 
I couldn't find the option in the manual by looking for output or file name. 

Thank you in advance, 
Anna

**Comment by stephaneguindon** [comment]
Hi Anna,
No, I haven't implemented these two options unfortunately. I guess that most people in need of these sorts of options have a script that (1) rename input files and (2) possibly create a directory, copy the input file in this folder plus the PhyML binary and (3) launch the analysis in this newly created directory. 
Regards,
-Stephane-

**Comment by nataquinones** [comment]
I'm also interested in an option to name the output files. Any chance of reconsidering this feature? 
There are applications in which this is necessary. For example, I'm running phyml with different options, from the same input file. If I want to run them in parallel, having no option to control the output name is problematic. Also, it is much more convenient to integrate with pipelines (i.e. `Snakemake`) if there's an option to specify the output path.
