### ISSUE TITLE
Can't compile in Linux

### ISSUE THREAD

**Issue by drelo** [stephaneguindon/phyml#11]
Dear Stephane, 

I downloaded the zip file and tried 
./configure and then make and got the following error. Do you know how to fix this? Thanks in advance.

I have zsh installed but now it's currently disabled I am using the default terminal in GNOME, Ubuntu 14.04. 

andrelo@mentat:~/Desktop/OMA/phyml-master$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for log in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for pdflatex... no
checking for latex... no
configure: WARNING: Documentation will not be built!
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for pow... yes
checking for rint... yes
checking for sqrt... yes
checking for strchr... yes
checking for strstr... yes
configure: "On arch x86_64-unknown-linux-gnu use MSSE = -msse"
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
sed: can't read ./ltmain.sh: No such file or directory
sed: can't read libtoolT: No such file or directory
andrelo@mentat:~/Desktop/OMA/phyml-master$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/andrelo/Desktop/OMA/phyml-master/missing aclocal-1.14 
/bin/bash: /home/andrelo/Desktop/OMA/phyml-master/missing: No such file or directory
make: *** [aclocal.m4] Error 127

**Comment by stephaneguindon** [comment]
Hi there,

You can use the script 'confphy' (just type ./confphy in your terminal).
That should help. Let me know if it doesn't.

Regards,

-Stephane-

**Comment by hedjour** [comment]
Have you the autotools install ?

**Comment by drelo** [comment]
I used ./confphy and it compiled, thanks for your help.

El vie., 18 de sept. de 2015 a la(s) 8:03 a. m., Jean-Emmanuel <
notifications@github.com> escribió:

> Have you the autotools install ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stephaneguindon/phyml/issues/11#issuecomment-141418740>
> .
>
-- 

Postdoctoral Associate

Instituto de Cs Ambientales y Evolutivas
Universidad Austral de Chile
Campus Isla Teja s/n
Valdivia, Chile
