### ISSUE TITLE
Segfault when computing --ancestral

### ISSUE THREAD

**Issue by blinard-BIOINFO** [stephaneguindon/phyml#110]
Hi Stephane,

In release 3.3.20190321, I get a segmentation fault when trying to compute ancestral states at at the step where the input tree is opened.
With the same input files, this problem is absent from previous version 3.3.20180621.

Compilation:

sh autogen.sh
./configure --enable-phyml; make; 

Execution:

`phyml --ancestral --no_memory_check --leave_duplicates -d nt -f e -o r -b 0 -v 0.0 -i extended_align.phylip -u extended_tree_withBL_withoutInterLabels.tree -c 4 -m GTR -a 0.433673`

Alignment/tree attached:
[data.zip](https://github.com/stephaneguindon/phyml/files/3574923/data.zip)

Here is the console output:

```


  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:				 extended_align.phylip
        . Data type:					 dna
        . Alphabet size:				 4
        . Sequence format:				 interleaved
        . Number of data sets:				 1
        . Nb of bootstrapped data sets:			 0
        . Model name:					 GTR
        . Proportion of invariable sites:		 0.000000
        . Number of subst. rate catgs:			 4
        . Gamma distribution parameter:			 0.437939
        . 'Middle' of each rate class:			 mean
        . Nucleotide equilibrium frequencies:		 empirical
        . Optimise tree topology:			 no
        . Evaluated tree:				 "user tree (extended_tree_withBL_withoutInterLabels.tree)"
        . Optimise branch lengths:			 no
        . Optimise substitution model parameters:	 yes
        . Run ID:					 none
        . Random seed:					 1567606630
        . Subtree patterns aliasing:			 no
        . Version:					 3.3.20190321
        . Byte alignment:				 16
        . AVX enabled:					 no
        . SSE enabled:					 yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////



. 6328 patterns found (out of a total of 10576 sites). 

. 4300 sites without polymorphism (40.66%).

. Reading tree... Segmentation fault      (core dumped)

```

**Comment by blinard-BIOINFO** [comment]
After some investigation, it seems the segfault is launched from
` t_tree *Read_Tree(char **s_tree)`
in  file src/io.c .

More precisely on line :
```
  if(tree->n_root)
    {
       [ ...]
       tree->n_root->b[2]->l->v = tree->n_root->b[0]->l->v;
```

**Comment by blinard-BIOINFO** [comment]
Possibly, it has been recently  corrected by this commit: daeb8a3897ca237983f3fc6e89c53672881d3dd

I will try with this recent fix.

**Comment by blinard-BIOINFO** [comment]
That's it ! It was corrected in july.

As this is a critical bug (crash with rooted trees), would it be possible to produce a new PhyML release on github  ? 

I need the conda package to be functionnal to include it as a dependency to RAPPAS conda package that I'm building now.

If @epruesse is OK, I will I will push an update to the bioconda recipe once this is done.

**Comment by stephaneguindon** [comment]
Hi Benjamin,
I've just created a new release that, hopefully, fixes these issues. I've also modified the format for the output file for ancestral sequences such that the marginal posterior probabilities are now given with full precision. Feel free to have a go and let me know if other issues come up.
