### ISSUE TITLE
phyML Input data

### ISSUE THREAD

**Issue by DarioUH-HI-2019** [stephaneguindon/phyml#112]
Dear Dr. Stéphane Guindon,

I hope you are doing well. My name is Dario and I am a Master's student at the University of Hawaii at Manoa. I have found really useful the program you have developed for creating a phylogenetic tree using the Maximum Likelihood algorithm. I would like to create a phylogeny using the complete genomes of 9 different Clavibacter species. My genomes are completely annotated. I was wondering if I can create this tree with complete genomes or do I have to first get only the core genome? If I have to get first the core genome, does phyML allow me to do that or do I have to use another program such as OrthoMCL or Get Homologues to locate the orthologues genes and then, do the alignment and finally use phyML to generate the tree? Please, I would really appreciate your help. Thank you so much beforehand.

**Comment by stephaneguindon** [comment]
Hi Dario,
Sorry for the delay in responding. PhyML does not allow you to get the core genome. You'll have to use other tools to build that. The input data for PhyML consist in one or several files, each of them containing a sequence alignment. The set of taxa considered has to be the same for all alignments.
Best regards,
-Stephane-
