### ISSUE TITLE
Autogenerated files in archive/redistributed

### ISSUE THREAD

**Issue by smoe** [stephaneguindon/phyml#113]
Hello,
a "make clean" cleans
src/Makefile.in
doc/Makefile.in
which is just perfect but these files are redistributed despite being autogenerated. Please consider to remove them. This makes the packaging for Debian a bit cleaner - no blocker, just a side-issue for the beauty of it all.
Cheers,
Steffen

**Comment by stephaneguindon** [comment]
Yep. Done. Thank you Steffen.
