### ISSUE TITLE
libhmsbeagle/beagle.h: No such file or directory

### ISSUE THREAD

**Issue by abrozzi** [stephaneguindon/phyml#116]
Dear Stephane,
I am sorry to borrow you. 
Installing `phyml-beagle` I encounter the following error I couldn't resolve:

```
./configure --enable-beagle; make clean; make;

.:  Building [phyml-beagle]. Version 3.3.20190909 :.

gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
In file included from main.c:33:0:
beagle_utils.h:9:33: fatal error: libhmsbeagle/beagle.h: No such file or directory
 #include "libhmsbeagle/beagle.h"
                                 ^
compilation terminated.
make[2]: *** [main.o] Error 1
```
I successfully installed `beagle` on my home following step-by-step the instructions of its repo in git:

`https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions`.

I set the path to the library as written in the tutorial:
```
export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
ab@guest:~/phyml$ env | grep LD_
LD_LIBRARY_PATH=/home/ab/lib:
```
The file it looks for `libhmsbeagle/beagle.h` is present in:
```
ab@guest:~/phyml$ ll /home/ab/beagle-lib/libhmsbeagle/beagle.h
-rw-rw---- 1 ab usr 62K Jan  8 12:06 /home/ab/beagle-lib/libhmsbeagle/beagle.h
```

Thanks infinitely in advance for any help,
-A

**Comment by stephaneguindon** [comment]
I'm afraid the BEAGLE is no longer supported by PhyML. I've just haven't had enough time to look after this part of the code unfortunately. Note however that the core of the likelihood calculation relies on vector-based calculations, in a similar manner as to what BEAGLE is doing.

**Comment by abrozzi** [comment]
OK! Thanks Stephane!
-A
