### ISSUE TITLE
running time with mpirun conflict

### ISSUE THREAD

**Issue by fermza** [stephaneguindon/phyml#118]
Hi Stephan,

we have noticed an issue with parallelization and running time. We have tried in different computers, and we couldn't quite put the finger on the issue until now. 
In short, whenever we try to run the command with 'mpirun -n #t phyml-mpi ....' [#t corresponding to the number of threads to use], we've noticed that if the number of threads used is greater than the number of cores, the running time is way (waaaaay) longer than using the threads = cores available. To clarify, in an i7 with 4 cores and 8 threads, it takes more than double time if we use -n 8 compared to -n 4. In a Ryzen with 8 cores and 16 threads, it takes also longer time to use -n 10 compared to -n 8. We have tried this also with different phyml versions (3.3.3:3.3.20170530+dfsg-2 and 3.3.3:3.3.20190321-2), running either on Ubuntu 18.04 or Ubuntu 19.04.
FYI, we are tipically running phylogenies with 1000-2700 protein sequences, around 200-400 positions, no boostraps. A complete typical command we use is:
'mpirun -n 8 phyml-mpi -i NAAT.phy -d aa -m WAG -a 4 --no_memory_check'
Do you have any insights on this? We would like to be able to optimize this, so any comments and help you can provide will be greatly appreciated. 
Best,
Fernando

**Comment by stephaneguindon** [comment]
Dear Fernando,
I am not a specialist of MPI unfortunately. Could it be that the bottleneck here has to do with the amount of memory space available?  
Regards,
-Stephane-

**Comment by fermza** [comment]
Thanks Stephane, I got from your answer you think this is a MPI issue rather than phyml-mpi. In that case I'll try to figure this out with some MPIist. If I find a fix I'll come back an post it here.

Best,
Fernando

**Comment by fermza** [comment]
Dear Stephane,
still didn't figure out the issue with MPI. However, running some other tests, we've noticed something else. When using a Ryzen 7000 with 8 cores and 16 threads, with the following command:
`phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`

the next message is printed in terminal:
`. Command line: phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`

and the process starts using only one thread. 

Now, if I use the command:
`phyml -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
(note is phyml rather than phyml-mpi)

the terminal prints:
`. Command line: /usr/lib/phyml/bin/phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
and the process starts with 8 threads! 

Something similar happens when using an i7 with 4 cores and 8 threads (using the 'phyml' command by itself, it shows that '/usr/lib/phyml/bin/phyml-mpi' is being used, and the process starts with 4 threads). 
Can you clarify how is this working, and if there is a way to modify it in order to get it to use all the threads available in the computer?

Thanks in advance,
Fernando

**Comment by yuyuqi-design** [comment]
> Dear Stephane,
> still didn't figure out the issue with MPI. However, running some other tests, we've noticed something else. When using a Ryzen 7000 with 8 cores and 16 threads, with the following command:
> `phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
> 
> the next message is printed in terminal:
> `. Command line: phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
> 
> and the process starts using only one thread.
> 
> Now, if I use the command:
> `phyml -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
> (note is phyml rather than phyml-mpi)
> 
> the terminal prints:
> `. Command line: /usr/lib/phyml/bin/phyml-mpi -i F2_EukTrypsinFull_g04_h09.phy -d aa -m WAG --no_memory_check`
> and the process starts with 8 threads!
> 
> Something similar happens when using an i7 with 4 cores and 8 threads (using the 'phyml' command by itself, it shows that '/usr/lib/phyml/bin/phyml-mpi' is being used, and the process starts with 4 threads).
> Can you clarify how is this working, and if there is a way to modify it in order to get it to use all the threads available in the computer?
> 
> Thanks in advance,
> Fernando

Hi Fernando and Stephane:
I have the same issue with the first one you mentioned. When I use phyml-mpi, no matter how many cores specified, it is always running with one core. And it will abort eventually with the error: ' The number of CPUs used in the MPI bootstrap analysis should be
. strictly greater than 1 (it is equal to 1 here).'
It is really confusing. Now I am running with non-paralell phyml. But it will take long time to finish the bootstrap analysis. Hope this issue can be fixed soon.

Yuqi

**Comment by stephaneguindon** [comment]
Dear Yuqi and Fernando,

I was never able to reproduce this issue on my side. Here are the different steps I used :

```
./configure --enable-mpi
make clean; make;
cd src/;
mpirun -n 4 ./phyml-mpi -i proteic -d aa -b 100 -c 1
```

The standard output is as follows:

. Running the analysis on 4 CPUs..                            
                                                           
. Command line: ./phyml-mpi -i proteic -d aa -b 100 -c 1    

and the analysis proceeds normally, using 4 CPUs as expected. From what I can see, it looks as if you are not using the mpi-run command properly. Please make sure you launch the analysis using "`mpirun -n X ./phyml-mpi -i ...`" (with X the number of CPUs) instead of just "`phyml-mpi -i ...`".

Regards,

-Stephane-
