### ISSUE TITLE
BEAGLE-enabled PhyML crashes when performing SPR tree search

### ISSUE THREAD

**Issue by alexhbnr** [stephaneguindon/phyml#12]
Hello,

I use a freshly compiled version of PhyML cloned from the GitHub repository (date: 19/07/15) and enabled the BEAGLE support for speeding up the likelihood calculations.
When running the BEAGLE-enabled PhyML with setting the "Tree topology search operations" to "Best of NNI and SPR" and 5 random starting trees, all of my data sets crash at some point with the following error code:

. Best_move < 0 !
. List size = 2
. 0x12c49c30 0x242d9b0
. 0x12c3c2b0 0x23fdc50
== Err. in file spr.c at line 4166 (function 'Evaluate_List_Of_Regraft_Pos_Triple')

The list size is varying based on the data set and the time when crashing. I cannot reproduce this behaviour when using the example data set delivered with PhyML. But the sample size in my data files is much larger and the alignment length much longer (>300 samples, alignment length > 2,000bp). BEAGLE itself should be the problem because I am able to run BEAST using the same library without any problems.

Is this behaviour due to my data sets (nucleotide alignments with gaps) or due to a bug in PhyML's spr.c?

Thanks in advance for your help,
Alex

**Comment by cms521** [comment]
Did anyone ever find a solution?

**Comment by stephaneguindon** [comment]
I would suggest trying recent versions of PhyML.
