### ISSUE TITLE
ancestral sequence calculation

### ISSUE THREAD

**Issue by yuyuqi-design** [stephaneguindon/phyml#122]
Hi,
I am using Phyml to get ancestral sequences, but I have the following error:
Probabilities do not sum to 1.0! Aborting.

My command is :
phyml -i trim2_outgroup_dropDupli.phy -d aa -q -b 100 -m LG -a 0.749 -f m --pinv 0.05 --ancestral

I would appreciate it if you could help me!

Yuqi

**Comment by stephaneguindon** [comment]
Dear Yuqi,
In case you are not using the latest commit version of PhyML, I recommend try this one out. Alternatively, please feel free to send me your data set so that I try and reproduce this issue on my side.
Regards,
-Stephane-
