### ISSUE TITLE
WARNING: PhyML binary is not in the list of compatibility

### ISSUE THREAD

**Issue by AlexWanghaoming** [stephaneguindon/phyml#125]
Hi,
It seems that the PhyML in the package can not be used. Also, the compatible versions: 20130103 20131022 20141009 20141029 20150501 20151222  can not be found in the [https://github.com/stephaneguindon/phyml/releases/tag/](url)

**Comment by AlexWanghaoming** [comment]
Counld you please offer a one of the version above?
Thanks

**Comment by stephaneguindon** [comment]
I am not sure what you mean by "can not be used". Please feel free to use the latest release. It'll compile on most operating systems.
