### ISSUE TITLE
Error compiling phyml-mpi

### ISSUE THREAD

**Issue by tanhuizhen** [stephaneguindon/phyml#126]
Hello,

I am facing errors installing phyml-mpi at the "make" step.

My computer runs macOS Sierra 10.12.6 and the following are my installation steps:
1. Install mpi
`conda install -c conda-forge mpi`

2. Install mpi version of phyml (v3.3.20190909 from GitHub)
`autoreconf -i;
./configure --enable-mpi --enable-phyml;
make;`

Errors pop up after the `make` step is performed.

Following the steps above, the 1st error was:
```
make;
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
.: Building [phyml-mpi]. Version 3.3.20190909 :.
mpicc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
/Users/fuzzywuzzy/miniconda2/bin/mpicc: line 282: x86_64-apple-darwin13.4.0-clang: command not found
make[2]: *** [main.o] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Then I installed mpich-mpicc ...
`conda install -c conda-forge mpich-mpicc`

and retried `make;` again, encountering the 2nd error:
```
ld: unknown option: -platform_version
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [phyml-mpi] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
I was told to update xcode to version 9.2 at some point during the installation process as well.

I appreciate any advice regarding these errors, should it be version incompatibility or otherwise.

Thank you very much.

Best,
Hui Zhen

**Comment by stephaneguindon** [comment]
Dear Hui Zhen,
It looks as if this problem has more to do with the OS than with PhyML itself. I'm afraid I can't run tests on my side (I only have a linux box).
Regards,
-Stephane-

**Comment by tanhuizhen** [comment]
Dear Stephane,

Alright, thanks for letting me know.

Best,
Hui Zhen
