### ISSUE TITLE
-1 appears in final phy_phyml_tree.txt 

### ISSUE THREAD

**Issue by NancyZxll** [stephaneguindon/phyml#128]
Hello, when I build a ML tree running for n bootstrap replicates, there are several -1 appearing in the final phy_phyml_tree.txt. For example when I set the bootstrap value to 1000, it shows like:
((seq1:0.03,seq2:0.01)-1:0.04,(seq3:0.01,(seq4:0.2,seq5:0.05)-1:0.2)1000:0.01);
((seq3,seq2),seq1,(seq4,seq5));

I suppose the value outside the right bracket is the bootstrap value, but why this value can be -1? I have searched online for long time, but no related answer has been found. Please advise~

**Comment by stephaneguindon** [comment]
It is unexpected indeed... Please let me know what version of PhyML you are using here and paste the command-line options as well.

**Comment by NancyZxll** [comment]
Thank you Stephane, I am using PhyML version 3.3.20190909 and the command-line I am using is:
`mpirun -n 25 phyml-mpi -i 08.clean.SNP.rmRecomb.matrix.sequential.phylip -b 100 -m GTR`

And, the output of prefix.phylip_phyml_tree.txt is like:

> (SRR7796531:0.04788994,((((((PROV247_DMS20612-V:0.04682148,(PROV061_DMS18785-V:0.00033635,(PROV099_DMS18810-V:0.00033636,GCF_003226135.1_ASM322613v1_genomic:0.00047094)27:0.00000001)100:0.04287042)100:0.11273716,(((PROV143_DMS18642-V:0.01768399,(PROV175_DMS18902-V:0.01629293,(PROV158_DMS18653-V:0.01377818,PROV178_DMS18904-V:0.01460923)96:0.00357509)64:0.00350423)100:0.01592978,(((PROV071_DMS20607-V:0.00063815,(PROV037_DMS18726-V:0.00094075,(PROV066_DMS18790-V:0.00087347,(PROV090_DMS18801-V:0.00080624,PROV191_DMS19274-V:0.00124348)11:0.00000001)14:0.00000001)18:0.00000001)89:0.00006713,(((PROV083_DMS18794-V:0.00000001,(PROV084_DMS18795-V:0.00003356,(PROV007_DMS18603-V:0.00000001,PROV008_DMS18604-V:0.00006713)95:0.00010070)37:0.00000001)100:0.00127766,((PROV235_DMS19285-V:0.00003356,(PROV246_DMS19287-V:0.00003356,(PROV238_DMS18693-V:0.00000001,(PROV232_DMS18688-V:0.00000001,(PROV184_DMS18909-V:0.00000001,PROV243_DMS18697-V:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)20:0.00000001)88:0.00006713,((PROV231_DMS19284-V:0.00000001,PROV240_DMS19286-V:0.00000001)-1:0.00003356,((PROV248_DMS19288-V:0.00000001,(PROV244_DMS19293-V:0.00000001,(PROV241_DMS18695-V:0.00000001,(PROV234_DMS18690-V:0.00000001,(PROV233_DMS18689-V:0.00000001,(PROV183_DMS18908-V:0.00000001,(PROV180_DMS18906-V:0.00000001,(PROV177_DMS18903-V:0.00000001,(PROV176_DMS18654-V:0.00000001,PROV249_DMS18699-V:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001)-1:0.00000001,(PROV237_DMS18692-V:0.00000001,PROV242_DMS18696-V:0.00000001)-1:0.00003356)15:0.00000001)19:0.00000001)100:0.00094110)80:0.00006679,(((PROV052_DMS18740-V:0.00003356,((PROV053_DMS18741-V:0.00000001,PROV054_DMS18742-V:0.00000001)-1:0.00000001,((PROV056_DMS18781-V:0.00006713,(PROV055_DMS18743-V:0.00000001,PROV057_DMS18782-V:0.00000001)-1:0.00000001)67:0.00003356,(PROV059_DMS18784-V:0.00016783,PROV058_DMS18783-V:0.00006713)22:0.00000001)9:0.00000001)7:0.00000001)68:0.00003340,(PROV041_DMS18729-V:0.00003356,(PROV043_DMS18731-V:0.00003356,PROV042_DMS18730-V:0.00000001)18:0.00000001)100:0.00013443)100:0.00124369,((PROV050_DMS18738-V:0.00013434,(PROV162_DMS18890-V:0.00003356,(PROV228_DMS18919-V:0.00000001,PROV048_DMS18736-V:0.00010069)17:0.00000001)72:0.00003349)100:0.00087360,(SRR4191398:0.00010064,(SRR4191386:0.00026855,SRR4191387:0.00000001)77:0.00003361)100:0.00222039)10:0.00000001)7:0.00000001)11:0.00000001)100:0.00696226,((PROV046_DMS18734-V:0.00003355,(PROV044_DMS18732-V:0.00000001,PROV051_DMS18739-V:0.00000001)-1:0.00000001)8:0.00000001,(PROV049_DMS18737-V:0.00003355,PROV047_DMS18735-V:0.00003355)33:0.00000001)100:0.01043701)100:0.02665814)100:0.20608103,(((GCF_000158055.1_ASM15805v1_genomic:0.05990919,PROV150_DMS18885-V:0.06237619)100:0.05906650,(PROV156_DMS18652-V:0.00028987,GCF_002417505.1_ASM241750v1_genomic:0.00136097)100:0.15651651)100:0.03079349,(PROV069_DMS20606-V:0.04997201,(PROV221_DMS18683-V:0.00211877,(PROV214_DMS18677-V:0.00070785,(PROV009_DMS20601-V:0.00033515,PROV040_DMS18728-V:0.00003480)100:0.00043743)100:0.00142170)100:0.04700140)100:0.10082906)100:0.01560109)63:0.00919931)97:0.01699617,(PROV118_DMS18877-V:0.05905613,((PROV196_DMS19276-V:0.06249931,PROV182_DMS18907-V:0.05896989)35:0.01439370,((PROV092_DMS18803-V:0.00247464,(PROV140_DMS18639-V:0.00040695,(PROV060_DMS19290-V:0.00037040,PROV075_DMS18621-V:0.00033671)99:0.00019907)100:0.00290549)100:0.04864603,((SRR4191412:0.00010090,SRR5168013:0.00000001)44:0.00000001,(SRR4191391:0.00010090,(SRR4191388:0.00087522,(SRR4191392:0.00013454,SRR4191390:0.00010090)58:0.00003365)56:0.00003362)56:0.00000001)100:0.05191633)100:0.01663816)28:0.01002820)100:0.06471498)100:0.02725363,(GCF_002265395.1_ASM226539v1_genomic:0.07747691,(((PROV163_DMS18891-V:0.00154938,(PROV270_DMS20614-V:0.00138110,(PROV194_DMS19291-V:0.00290378,(PROV018_DMS18606-V:0.00010087,PROV022_DMS19267-V:0.00006727)100:0.00215969)100:0.00046955)77:0.00003302)96:0.00015685,(PROV160_DMS18888-V:0.00077405,(PROV021_DMS18609-V:0.00117811,(PROV115_DMS18874-V:0.00144840,((PROV016_DMS19266-V:0.00003362,PROV015_DMS19289-V:0.00000001)100:0.00117833,(PROV112_DMS24322-V:0.00023542,PROV245_DMS18698-V:0.00000001)100:0.00090876)46:0.00003359)11:0.00000001)19:0.00000001)100:0.00102161)100:0.06538671,(PROV153_DMS18649-V:0.06209995,((PROV081_DMS20609-V:0.00000001,PROV082_DMS18624-V:0.00000001)-1:0.00000001,(PROV074_DMS19268-V:0.00016818,PROV073_DMS18620-V:0.00003363)30:0.00000001)100:0.06447782)91:0.01885958)98:0.01868154)100:0.05460276)87:0.01645457,((ERR2125625:0.00000001,GCF_900455265.1_52400_A01_genomic:0.00000001)-1:0.07426940,(PROV029_DMS18719-V:0.00014001,(PROV026_DMS18613-V:0.00006723,PROV030_DMS18720-V:0.00003361)76:0.00002807)100:0.08673525)100:0.02661137)100:0.04814595,((PROV031_DMS18721-V:0.00273824,(((PROV279_DMS26884-V:0.00000001,PROV280_DMS26885-V:0.00000001)-1:0.00010082,((PROV277_DMS26882-V:0.00000001,PROV006_DMS18602-V:0.00010083)56:0.00003361,(PROV278_DMS26883-V:0.00003361,PROV275_DMS26880-V:0.00000001)13:0.00000001)1:0.00000001)61:0.00003350,(PROV001:0.00016805,((PROV101_DMS18812-V:0.00000001,PROV109_DMS18869-V:0.00000001)-1:0.00010084,(PROV102_DMS18813-V:0.00000001,(PROV100_DMS18811-V:0.00000001,PROV103_DMS18863-V:0.00000001)-1:0.00000001)-1:0.00013444)73:0.00003360)75:0.00003372)100:0.00442674)88:0.00023876,(PROV142_DMS18641-V:0.00050457,PROV157_DMS18643-V:0.00030251)100:0.00120861)100:0.05079891)100:0.02223225,(PROV229_DMS18920-V:0.00003411,PROV165_DMS18893-V:0.00003317)100:0.04437506);

You can find there are several -1 inside the text file. The same thing happens (including some -1) when I run the same command line for three datasets.

**Comment by stephaneguindon** [comment]
I suspect that these -1s appear in subtrees containing identical sequences (PhyML output should give you some information about which sequences are identical to what). Is it the case? If it is indeed, then you can safely ignore these -1 (or interpret them as the bootstrap values you'd get if the grouping of sequences in these particular subtrees in a fully random fashion).

**Comment by NancyZxll** [comment]
ah~ right right, it indeed gives me this information before~ says~~ those are identical sequences.
Thank you Stephane! So much:D

**Comment by stephaneguindon** [comment]
You're welcome!
