### ISSUE TITLE
Compiling mpi version undefined reference error

### ISSUE THREAD

**Issue by PrestonMcDonald** [stephaneguindon/phyml#129]
make  all-recursive
make[1]: Entering directory `/home/xxx/software/phyml'
Making all in src
make[2]: Entering directory `/home/xxx/software/phyml/src'

.:  Building [phyml]. Version 3.3.20200621 :.

mpicc  -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native   -o phyml   -lm
icc: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
make[2]: *** [phyml] Error 1
make[2]: Leaving directory `/home/xxx/software/phyml/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/xxx/software/phyml'
make: *** [all] Error 2

**Comment by stephaneguindon** [comment]
Try `make clean` first and then `make`

**Comment by halocaridina** [comment]
Just ran into the same issue that @PrestonMcDonald describes above on a CentOS 8 system with the Summer 2020 release. In contrast, Autumn 2019 release compiled fine using the exact same set of command (i.e., those on the front page of the project.

Hope this helps ID where the issue lies.

**Comment by stephaneguindon** [comment]
It looks as if @PrestonMcDonald  mis-configured the compilation here. Since it is phyml (not phyml-mpi) that is built here, the compiler shouldn't be mpicc. Can you please tell me exactly which options you used here when running the "configure" command? Thanks.

**Comment by halocaridina** [comment]
As per README.md with freshly unpacked source:
**`sh ./autogen.sh`**
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:16: installing './compile'
configure.ac:14: installing './config.guess'
configure.ac:14: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

**`autoreconf -I`**

**`./configure --enable-mpi --enable-phyml`**
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for log in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for pdflatex... no
checking for latex... no
configure: WARNING: Documentation will not be built!
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for pow... yes
checking for rint... yes
checking for sqrt... yes
checking for strchr... yes
checking for strstr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands

**`make`**
make  all-recursive
make[1]: Entering directory '/tmp/phyml-3.3.20200621'
Making all in src
make[2]: Entering directory '/tmp/phyml-3.3.20200621/src'


.:  Building [phyml]. Version 3.3.20200621 :.


mpicc  -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native   -o phyml   -lm
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/Scrt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1690: phyml] Error 1
make[2]: Leaving directory '/tmp/phyml-3.3.20200621/src'
make[1]: *** [Makefile:363: all-recursive] Error 1
make[1]: Leaving directory '/tmp/phyml-3.3.20200621'
make: *** [Makefile:304: all] Error 2
zsh: exit 2

**Comment by stephaneguindon** [comment]
Would you mind trying 'make clean;' before 'make'? Thanks.-------- Message original --------De : "Scott R. Santos" <notifications@github.com>Date : jeu. 12 nov. 2020 à 20:20À : stephaneguindon/phyml <phyml@noreply.github.com>Cc : Stephane Guindon <stephane.guindon@gmail.com>, Comment <comment@noreply.github.com>Objet : Re: [stephaneguindon/phyml] Compiling mpi version undefined reference error (#129)
As per README.md with freshly unpacked source:
sh ./autogen.sh
autoreconf: Entering directory .' autoreconf: configure.ac: not using Gettext autoreconf: running: aclocal --force autoreconf: configure.ac: tracing autoreconf: configure.ac: not using Libtool autoreconf: running: /usr/bin/autoconf --force autoreconf: running: /usr/bin/autoheader --force autoreconf: running: automake --add-missing --copy --force-missing configure.ac:16: installing './compile' configure.ac:14: installing './config.guess' configure.ac:14: installing './config.sub' configure.ac:5: installing './install-sh' configure.ac:5: installing './missing' src/Makefile.am: installing './depcomp' autoreconf: Leaving directory .'
autoreconf -I
./configure --enable-mpi --enable-phyml
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for log in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for pdflatex... no
checking for latex... no
configure: WARNING: Documentation will not be built!
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for pow... yes
checking for rint... yes
checking for sqrt... yes
checking for strchr... yes
checking for strstr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
make
make  all-recursive
make[1]: Entering directory '/tmp/phyml-3.3.20200621'
Making all in src
make[2]: Entering directory '/tmp/phyml-3.3.20200621/src'
.:  Building [phyml]. Version 3.3.20200621 :.
mpicc  -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native   -o phyml   -lm
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/Scrt1.o: In function _start': (.text+0x24): undefined reference to main'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1690: phyml] Error 1
make[2]: Leaving directory '/tmp/phyml-3.3.20200621/src'
make[1]: *** [Makefile:363: all-recursive] Error 1
make[1]: Leaving directory '/tmp/phyml-3.3.20200621'
make: *** [Makefile:304: all] Error 2
zsh: exit 2

**Comment by halocaridina** [comment]
Sure but no difference again using clean source:

**`sh ./autogen.sh`**
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:16: installing './compile'
configure.ac:14: installing './config.guess'
configure.ac:14: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

**`autoreconf -i`**

**`./configure --enable-mpi --enable-phyml`**
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for log in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for pdflatex... no
checking for latex... no
configure: WARNING: Documentation will not be built!
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for pow... yes
checking for rint... yes
checking for sqrt... yes
checking for strchr... yes
checking for strstr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands

**`make clean`**
Making clean in src
make[1]: Entering directory '/tmp/phyml-3.3.20200621/src'
test -z "phyml" || rm -f phyml
rm -f *.o
make[1]: Leaving directory '/tmp/phyml-3.3.20200621/src'
make[1]: Entering directory '/tmp/phyml-3.3.20200621'
make[1]: Nothing to be done for 'clean-am'.
make[1]: Leaving directory '/tmp/phyml-3.3.20200621'

**`make`**
make  all-recursive
make[1]: Entering directory '/tmp/phyml-3.3.20200621'
Making all in src
make[2]: Entering directory '/tmp/phyml-3.3.20200621/src'


.:  Building [phyml]. Version 3.3.20200621 :.


mpicc  -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native   -o phyml   -lm
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/Scrt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1690: phyml] Error 1
make[2]: Leaving directory '/tmp/phyml-3.3.20200621/src'
make[1]: *** [Makefile:363: all-recursive] Error 1
make[1]: Leaving directory '/tmp/phyml-3.3.20200621'
make: *** [Makefile:304: all] Error 2
zsh: exit 2

**Comment by stephaneguindon** [comment]
Mmmm... Sorry I missed it : please remove '--enable-phyml' in the configure option. That should work (I hope).

**Comment by halocaridina** [comment]
Yes, removing the '--enable-phyml' config option allowed successful compilation of the Summer 2020 release. However, having that option in place allowed the Autumn 2019 release to successfully compile, producing an executable named phyml-mpi that successfully ran with mpirun. Haven't diff'ed the Makefiles to see what's different.....

Suggest revising the README in the release and the front page and closing this issue. Thank you again.

**Comment by stephaneguindon** [comment]
Great! 
I'll probably replace '--enable-mpi' with '--enable-phyml-mpi' so as to make it clear that the MPI option only applies to PhyML and not to PhyREX not PhyTime.
