### ISSUE TITLE
problem parsing command line arguments

### ISSUE THREAD

**Issue by sdemita** [stephaneguindon/phyml#130]
When I run the following 3 commands, PhyML runs fine::

    $ phyml -i i -d nt -m -t 4 HKY85
    $ phyml -i i -d nt -m HKY85 -t 4
    $ phyml -i i -d nt -t 4 -m TN93

But when I run this::

    $ phyml -i i -d nt -m TN93 -t 4

I get the error::

    . The Ts/Tv ratio must be a positive number.

The file i is a random alignment I use for testing purpose; I run version 3.3.20200621 which I recently pulled from master on Linux. Previously I didn't have this error with the same command, the same file and the same system.

**Comment by stephaneguindon** [comment]
Thanks for letting me know. I have fixed these issues in the latest commit 482e06a7afec9513fbddeb2311cfee3c8a1bf314
