### ISSUE TITLE
Packaging PhyML

### ISSUE THREAD

**Issue by V-Z** [stephaneguindon/phyml#143]
Not really an issue, I just inform that I package PhyML for openSUSE GNU/Linux:

- https://software.opensuse.org/search?utf8=%E2%9C%93&baseproject=openSUSE%3ALeap%3A15.3&q=PhyML
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML-mpi
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML-phyrex
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML-phytime
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML-rf
- https://build.opensuse.org/package/show/home:vojtaeus/PhyML-test

I hope to submit the packages soon into [scientific repository](https://build.opensuse.org/project/show/science).

**Comment by stephaneguindon** [comment]
Thanks!
