### ISSUE TITLE
Unable to write file

### ISSUE THREAD

**Issue by SticaC** [stephaneguindon/phyml#144]
I keep getting an error message:

Unable to write file.
Operation aborted.

I am unsure what the issue is. I am uploading a phylip alignment created in Geneious Prime. I have attached my alignment in .txt format for reference.

Thanks
Caleb

[DENV2_WG_alignement_complete_wB - Copy.txt](https://github.com/stephaneguindon/phyml/files/6722737/DENV2_WG_alignement_complete_wB.-.Copy.txt)

**Comment by stephaneguindon** [comment]
The alignment file is in a format that PhyML cannot read. Please ask Geneious dev to fix this issue.
