### ISSUE TITLE
Output pairwise distance matrix

### ISSUE THREAD

**Issue by wdenggithub** [stephaneguindon/phyml#145]
Hi,

I have been using PhyML3.0 for more than 10 years, it's a great program. I think that, when I started it, I wanted to have an output of pairwise distance matrix. With your help, there was an option "GENEIOUS" in main.c file. When I compiled the source code, I included "-DGENEIOUS" in "DEFS=", then the program will output the distance matrix, which is very important in our research. Now, I want to upgrade the program to the most recent version. But there is no "GENEIOUS" anymore. Could you please guide me how to set it up to output the distance matrix?

Best Regards,

Wenjie Deng

**Comment by stephaneguindon** [comment]
I've just added the option '--print_mat_and_exit'. See commit 5a78b552aeef4d996585292041cc7a8900a768b6

**Comment by wdenggithub** [comment]
Thank you so much. I really appreciate.

Wenjie
