### ISSUE TITLE
Possible bug in alrt.c Statistics_To_Probabilities function Line 936?

### ISSUE THREAD

**Issue by derreisende77** [stephaneguindon/phyml#147]
Having had a quick look over the code I wonder if the code in Line 936 is correct:
`else if(in>0.000982 && in<0.00393) `

If it should follow all the other if statements you are missing the case where in == 0.000982 and it should be like:
`else if(in>=0.000982 && in<0.00393) `

**Comment by stephaneguindon** [comment]
Yes, indeed. I'll fix this. Note however that, strictly speaking, most decimal numbers do not have an exact binary representation. Hence, I usually try to avoid testing for equality between double precision variables.
Thanks for spotting this issue though!
