### ISSUE TITLE
Configure Issue--Using Big Sur 

### ISSUE THREAD

**Issue by mattwgreen** [stephaneguindon/phyml#148]
Hi There,

I'm building phyml using the summer 2020 release, but I am receiving the error code below when configuring the program. I'm using a MacBook Air M1 with Big Sur. Would be glad to to provide additional information.

Thanks,
Matt

.:  Building [phyml]. Version 3.3.20200621 :.

gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
clang: error: the clang compiler does not support '-march=native'
make[2]: *** [main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by stephaneguindon** [comment]
I'm afraid I have a very limited knowledge of compilation options on the different platforms. I suggest you try replacing 
DEFAULT_VECTOR_FLAG="-march=native"
with
DEFAULT_VECTOR_FLAG="-mavx2"
in 'configure.ac' and re-compile. Let me know if this doesn't help.
