### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by monpau** [stephaneguindon/phyml#15]
Hi Stephane, 

when trying to run ./confphy after doing git clone, I'm getting this error:

>gcc  -I. -I..     -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized  -MT mcmc.o -MD -MP -MF .deps/mcmc.Tpo -c -o mcmc.o mcmc.c
>mcmc.c: In function ‘MCMC_Complete_MCMC’:
>mcmc.c:4499:25: error: ‘t_mcmc’ has no member named ‘num_move_phyrex_multi_traj’
>   mcmc->move_weight[mcmc->num_move_phyrex_multi_traj]            = 0.0;
>                         ^
>mcmc.c:4500:25: error: ‘t_mcmc’ has no member named ‘num_move_phyrex_flip’
>   mcmc->move_weight[mcmc->num_move_phyrex_flip]                  = 0.0;
>                         ^
>Makefile:1665: recipe for target 'mcmc.o' failed
>make[2]: *** [mcmc.o] Error 1
>make[2]: Leaving directory '/home/jope/soft/phyml/src'
>Makefile:388: recipe for target 'all-recursive' failed
>make[1]: *** [all-recursive] Error 1
>make[1]: Leaving directory '/home/jope/soft/phyml'
>Makefile:319: recipe for target 'all' failed
>make: *** [all] Error 2

I'm not sure if it is my fault or there's something funny with the code. Do you have any idea how to solve it? 

Thank you.

**Comment by stephaneguindon** [comment]
Hi there,

Sure. My mistake. I've fixed it now. Please feel free to update.

Regards,

-Stephane-
