### ISSUE TITLE
Wrong distance matrix output

### ISSUE THREAD

**Issue by wdenggithub** [stephaneguindon/phyml#152]
Hi Stephane,

Thanks for putting on the distance matrix output. I downloaded the most recent version of PhyML and tested on the output. It seems that the output is not correct, which is not triangular symmetry and some distances between sequence itself are not 0.  Attached please find an example output. 

The other issue is that it outputs the distance matrix and exit, no tree output. Could I have the results that outputs the distance matrix before the optimization, tree estimation and the distance matrix after the optimization? 

Best regards,

Wenjie Deng
[example_output.txt](https://github.com/stephaneguindon/phyml/files/7035359/example_output.txt)

**Comment by stephaneguindon** [comment]
Dear Wenjie,
There was a problem indeed. The matrix produced was in fact that modified by the BioNJ algorithm, explaining the lack of symmetry and the non-zero outputs on the diagonal. It should be fixed now. Please see 669ae30655d12e79333487ec0e3227044a47d974 and let me know if there are remaining issues.

**Comment by stephaneguindon** [comment]
Yes, commenting out the `exit(-1)` should work as expected.
By default, PhyML removes the duplicate sequences before launching the reconstruction so as to speed up the calculation. You may want to try the `--leave_duplicates` option if leaving the duplicated sequences during the analysis is more convenient for you.

**Comment by wdenggithub** [comment]
Dear Stephane,

It works perfectly. Thanks so much for your help. I really appreciate!

Wenjie

**Comment by stephaneguindon** [comment]
Great!
