### ISSUE TITLE
Branch support not available?

### ISSUE THREAD

**Issue by SticaC** [stephaneguindon/phyml#153]
I have used PhyML with several datasets using aLRT SH-like for branch support values. However with only one of my datasets, when I open it in FigTree, I cant get the branch support values. It usually pops up on opening the file, but for this one dataset, it does not. I have rerun the tree a couple times and it is always the same result. 

Find attached the input file as a .txt, as well as the zipped output.

Thanks
Caleb Stica

[DENV3_WG_alignement_complete.txt](https://github.com/stephaneguindon/phyml/files/7064116/DENV3_WG_alignement_complete.txt)
[denv3_wg_alignement_complete_phy_phyml_try2.zip](https://github.com/stephaneguindon/phyml/files/7064117/denv3_wg_alignement_complete_phy_phyml_try2.zip)

**Comment by stephaneguindon** [comment]
It looks as if you're using an outdated version of PhyML. A more recent one will give you the branch support you're after. I suggest you use the latest commit (or the latest release) from the GitHub repo instead of the one on the ATGC web server.
