### ISSUE TITLE
Adjusting README for mpi compilation

### ISSUE THREAD

**Issue by justNo4b** [stephaneguindon/phyml#154]
At least in my system (Ubuntu 18.04.5 LTS), when trying to use suggesting lines for compiling mpi version (`./configure --enable-phyml-mpi`) i was getting the following response:
`configure: WARNING: unrecognized options: --enable-phyml-mpi`, and if followed by `make` it compiled non-mpi version

After a bit of dig up in the file, I used `./configure --enable-mpi` and was able to make mpi version.

Maybe a note of this could be included in the README

**Comment by stephaneguindon** [comment]
`--enable-mpi` is not in the list of available options. `--enable-phyml-mpi` is the option you need to use here indeed. Are you using a recent version of the code?

**Comment by inspirewind** [comment]
I use the Summer 2020 release version, after running `./autogen.sh`, the configure file has this content

![image](https://user-images.githubusercontent.com/37958868/131540229-1bf60b67-d15d-436c-94c2-2c253f8e83a3.png)

Maybe the right code that can express the meaning in the README is `./configure --enable-mpi --enable-phyml`

**Comment by justNo4b** [comment]
> --enable-mpi is not in the list of available options. --enable-phyml-mpi is the option you need to use here indeed. Are you using a recent version of the code?
After some more checking, I found out that it is exactly right.
I downloaded not the latest version, but a `Summer 2020 release`. And at the same time looked not on README of the dowloaded version, but the _dev one (on the github website).
It was really dumb of me, sorry for wasting your time
