### ISSUE TITLE
Segfault in bootstrap analysis

### ISSUE THREAD

**Issue by afmagee** [stephaneguindon/phyml#155]
I was trying to run some nonparametric bootstrapping and I am encountering a segfault. The ML analysis runs fine, as do aLRT and other branch-support approaches.

I built the most recent commit (544982d) on both my machine running Ubuntu 18 and a cluster running centOS 7. Locally I tried both phyml and phyml-mpi. In all cases I encountered a segfault as the bootstrap analysis began.

Some (crude/coarse) tracing of the non-mpi segfault suggests it happens when `Bootstrap()` calls `Lk(NULL,boot_tree);` on 3241 in `utilities.c`.

**Comment by stephaneguindon** [comment]
Thanks for signaling this problem. It should be fixed in the latest commit 46fa1b33e5da2794ec374e387261a4fce6949e2b
