### ISSUE TITLE
Versioning error again

### ISSUE THREAD

**Issue by protist** [stephaneguindon/phyml#158]
Hi @stephaneguindon, looks like you forgot to bump the version number in `configure.ac` again. I built and installed the latest `3.3.20211231`, and it's reporting the old version.
```
$ phyml-mpi --version


. Running the analysis on 1 CPU..
. This is PhyML version 3.3.20211118.
``

**Comment by stephaneguindon** [comment]
Damn it! I keep on forgetting to do that... I'm fixing it right now.

**Comment by protist** [comment]
> Damn it! I keep on forgetting to do that... I'm fixing it right now.

No worries! Thanks for the continued development!
