### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bosborne** [stephaneguindon/phyml#16]
Just downloaded and unzipped phyml-master.zip, then:

briano - ~/Downloads/phyml-master
5228 > ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

Looks like there are some broken links in the directory.

**Comment by bosborne** [comment]
After "git clone":

briano - ~/git/phyml
5086 > ./confphy
+ aclocal
./confphy: line 3: aclocal: command not found
+ autoheader
./confphy: line 4: autoheader: command not found
+ autoconf -f
./confphy: line 5: autoconf: command not found
+ libtoolize
./confphy: line 6: libtoolize: command not found
+ automake -f --add-missing
./confphy: line 7: automake: command not found
+ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
+ make clean
make: *** No rule to make target `clean'.  Stop.
+ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by stephaneguindon** [comment]
Please run ./autogen.sh first from the phyml/ directory. You need autotools and automake packages installed on your machine.
