### ISSUE TITLE
Unexpected error: no inferred tree result file.

### ISSUE THREAD

**Issue by CarlsenA** [stephaneguindon/phyml#161]
Hello! For two days now, I have been getting the same error on the online version:
"Unexpected error: no inferred true result file.
phyml: optimize.c:2440: Br_Len_Spline: Assertion 'u < v' failed."
Moreover, I downloaded different files, including those for which trees have already been built, every time this error pops up.

**Comment by stephaneguindon** [comment]
Please send me your sequence file and model parameters so that I try and reproduce this issue on my side.

**Comment by CarlsenA** [comment]
[Delta_baeys_clean_97.zip](https://github.com/stephaneguindon/phyml/files/7985666/Delta_baeys_clean_97.zip)
Substitution model GTR, Gamma 4, aLRT SH-like, NNI (although I don't see where it can be marked now).

**Comment by stephaneguindon** [comment]
I could not reproduce this issue on my side. It's hard to tell what went wrong as I am not sure which "online version" of PhyML you are referring to. 

Please find the inferred tree and stats files attached here.

[Delta_baeys_clean_97.phy_phyml_tree.txt](https://github.com/stephaneguindon/phyml/files/8013810/Delta_baeys_clean_97.phy_phyml_tree.txt)
[Delta_baeys_clean_97.phy_phyml_stats.txt](https://github.com/stephaneguindon/phyml/files/8013811/Delta_baeys_clean_97.phy_phyml_stats.txt)

**Comment by CarlsenA** [comment]
I meant this version http://www.atgc-montpellier.fr/phyml/
And I keep getting this error when uploading any sequences to the site
But I downloaded PhyML-3.1, and everything works fine here, thank you!
