### ISSUE TITLE
Compilation for non-AMD/Intel CPUs

### ISSUE THREAD

**Issue by V-Z** [stephaneguindon/phyml#165]
Hello,
I'm [packaging PhyML for openSUSE GNU Linux](https://build.opensuse.org/package/show/home:vojtaeus/PhyML) and for "standard" architectures (AMD x86) it works fine, but for other architectures --- ARM, PowerPC and RISC-V I get various compilation errors (similar to #164). Do I get it right that PhyML is not supposed to work on non-AMD x86 architectures? Or is this somehow (easily) fixable?

**Comment by stephaneguindon** [comment]
Would you mind sharing more information on the computer and OS on which you tried to compile, along with the output of the ./configure and make commands? That would help me to find out where the problem comes from. Thank you.

**Comment by V-Z** [comment]
I use [openSUSE Build Service](https://build.opensuse.org/), [on-line service doing compilation and packaging](https://en.opensuse.org/openSUSE:Build_Service_Tutorial), so I don't do it on my machine. It is running openSUSE GNU Linux, but it can build SW also for another Linux distributions.

If You look at

* https://build.opensuse.org/package/show/home:vojtaeus/PhyML
* https://build.opensuse.org/package/show/home:vojtaeus/PhyML-mpi
* https://build.opensuse.org/package/show/home:vojtaeus/PhyML-phyrex
* https://build.opensuse.org/package/show/home:vojtaeus/PhyML-phytime
* https://build.opensuse.org/package/show/home:vojtaeus/PhyML-rf

and click on red links labeled "failed" (**Build Results** column on the right) --- You get to output of whole compilation, including `./configure` and `make`.

**Comment by martin-g** [comment]
Here is a patch that I made to be able to build on Linux ARM64 for Bioconda - https://github.com/bioconda/bioconda-recipes/pull/48554/files#diff-4871c3e819b573e5c6d37415e0e38ee22dcbb34b5abe61006b9fbe484381b664
I guess it should work for Mac ARM64 too.
It uses https://github.com/DLTcollab/sse2neon/ to translate SSE to NEON instructions.
Please let me know if you'd like me to open a PR with the changes!

**Comment by stephaneguindon** [comment]
Yes, please do. Thanks.

**Comment by martin-g** [comment]
OK! I will do it in the next few days!

**Comment by martin-g** [comment]
https://github.com/stephaneguindon/phyml/pull/194
