### ISSUE TITLE
Libtoolize not found on OSX 10.11.1

### ISSUE THREAD

**Issue by uvesten** [stephaneguindon/phyml#17]
Tried to build phyml on OSX. Unfortuntely, libtoolize is not found on that platform. 

However, installing libtool from homebrew (`brew install libtool` )solves the problem, together with changing line 6 of `confphy` from `libtoolize` to `glibtoolize`. 

Maybe add an extra confphy for osx with the file already in, or add a checking step to the script to test which of `libtoolize` or `glibtoolize` is available.

**Comment by stephaneguindon** [comment]
Hi there,
Thanks for letting me know. I've switched to using autoreconf which,
hopefully, does a better job than confphy on OS X. I haven't tested it
though so in case you want to try it, please update and type './autogen.sh'.
Regards,
-Stephane-

**Comment by terrycojones** [comment]
Running `./configure` on the 20160530 tarball at https://github.com/stephaneguindon/phyml/archive/v3.2.20160530.tar.gz results in:

```
config.status: executing libtool commands
sed: ./ltmain.sh: No such file or directory
sed: libtoolT: No such file or directory
```

It looks like `ltmain.sh` should have been included in the distribution?  Running `./autogen.sh` first creates `ltmain.sh` and allows configure to run cleanly.
