### ISSUE TITLE
How to calibrate the thousands of tips in phytime input file

### ISSUE THREAD

**Issue by biozhajie** [stephaneguindon/phyml#171]
Hi,
I have more than one thousands of sequences to be estimated a time tree using phytime, with a known sample date for each sequence. Now I want to use these sample dates to calibrate these thousands of tips, can anyone tell me how to conduct this calibration in input file?

**Comment by stephaneguindon** [comment]
You can use the "test" tool (that can be generated using ./configure --enable-test; make clean; make;). This tool allows you to read in sequence names and corresponding dates in a file with two columns and prints out the same information in a XML format that you can copy and paste in the XML configuration file. You will need to dig in a little in the file main.c (search for #elif(TEST)) but it shouldn't be too hard to get what you need.
