### ISSUE TITLE
Err. in file 'make.c' (line 94)

### ISSUE THREAD

**Issue by yardeng96** [stephaneguindon/phyml#177]
I recieve this error when trying to build a tree. 
line 94 in make.c file looks like this:  tree->_plk0        = _aligned_malloc(ns / sz * sizeof(__m128d),BYTE_ALIGN);
Any ideas on how to solve this issue?

**Comment by stephaneguindon** [comment]
It doesn't look like an error message generated by PhyML. Any chance you could post the standard output along with the command-line?

**Comment by yardeng96** [comment]
Command line: phyml -i alignment.txt -d aa --no_memory_check





  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:                             UPO-alignment-numbered-no-dup.txt
        . Data type:                                     aa
        . Alphabet size:                                 20
        . Sequence format:                               interleaved
        . Number of data sets:                           1
        . Nb of bootstrapped data sets:                  0
        . Compute approximate likelihood ratio test:     yes (aBayes branch supports)
        . Model name:                                    LG
        . Proportion of invariable sites:                0.000000
        . RAS model:                                     discrete Gamma
        . Number of subst. rate catgs:                   4
        . Gamma distribution parameter:                  estimated
        . 'Middle' of each rate class:                   mean
        . Amino acid equilibrium frequencies:            model
        . Optimise tree topology:                        yes
        . Starting tree:                                 BioNJ
        . Add random input tree:                         no
        . Optimise branch lengths:                       yes
        . Minimum length of an edge:                     1e-08
        . Optimise substitution model parameters:        yes
        . Run ID:                                        none
        . Random seed:                                   1663760760
        . Subtree patterns aliasing:                     no
        . Version:                                       3.3.20211231
        . Byte alignment:                                16
        . AVX enabled:                                   no
        . SSE enabled:                                   yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////



. 9411 patterns found (out of a total of 11266 sites).

. 2410 sites without polymorphism (21.39%).


. Computing pairwise distances...

. Building BioNJ tree...
. Err. in file 'make.c' (line 94)
. PhyML finished prematurely.


in another attempt with a different alignment (running the same command) I receive a segmentation fault error.

**Comment by stephaneguindon** [comment]
Would you mind updating the version of PhyML you're running and trying again?

**Comment by yardeng96** [comment]
Updated and ran again. Error changed:

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:                             alignment.txt
        . Data type:                                     aa
        . Alphabet size:                                 20
        . Sequence format:                               interleaved
        . Number of data sets:                           1
        . Nb of bootstrapped data sets:                  0
        . Compute approximate likelihood ratio test:     yes (aBayes branch supports)
        . Model name:                                    LG
        . Proportion of invariable sites:                0.000000
        . RAS model:                                     discrete Gamma
        . Number of subst. rate catgs:                   4
        . Gamma distribution parameter:                  estimated
        . 'Middle' of each rate class:                   mean
        . Amino-acid equilibrium frequencies:            empirical
        . Optimise tree topology:                        yes
        . Starting tree:                                 BioNJ
        . Add random input tree:                         no
        . Optimise branch lengths:                       yes
        . Minimum length of an edge:                     1e-08
        . Optimise substitution model parameters:        yes
        . Run ID:                                        none
        . Random seed:                                   1663846136
        . Subtree patterns aliasing:                     no
        . Version:                                       3.3.20220408
        . Byte alignment:                                32
        . AVX enabled:                                   yes
        . SSE enabled:                                   yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////



. Err. in file 'make.c' (line 62)
. PhyML finished prematurely.

**Comment by stephaneguindon** [comment]
It could be the case that the number of sequences to be analysed is too large for PhyML here and/or the sequences are too long. How many sequences do you have and how long are they?

**Comment by yardeng96** [comment]
There are 1100 sequences with an average of 350 aa.

**Comment by stephaneguindon** [comment]
The maximum number of sequences is set to 4000 but it could be that there is not enough RAM on the computer you are using in order to allocate the required memory space. You could try with no rate variation across sites by setting the number of classes of the discrete gamma distribution to 1 (instead of 4). Let me know if this helps.

**Comment by yardeng96** [comment]
I managed to avoid the issue by removing some sequences that were much longer than the average sequence in my alignment. after removing them I ran the tree with the same script as in the beginning. This solution is sufficient for me so I will leave this problem for now. Thanks a lot for your help!

**Comment by stephaneguindon** [comment]
Great!
