### ISSUE TITLE
make command error: libtools

### ISSUE THREAD

**Issue by ademcan** [stephaneguindon/phyml#18]
Hi, thank you for this very helpful tool.

I am trying to compile Phyml from the sources to generate and use the phyml-mpi version.
When I run the "make" command, it ends up with the following error :

make[2]: LIBTOOL@: Command not found
make[2]: *** [phyml-mpi] Error 127
make[2]: Leaving directory `/home/[USERNAME]/bin/phyml/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/[USERNAME]/bin/phyml'
make: *** [all] Error 2

Althought libtools is correctly installed in the machine.
Do you know how one could solve this issue ? Otherwise, isn't it possible to also provide the phyml-mpi binary in the github repository ?
Thank you.

**Comment by stephaneguindon** [comment]
Hi there,

Can you please post what the output of ./configure --enable-mpi is?

Regards,

-Stephane-

**Comment by ademcan** [comment]
Hi Stephan,

I attached the output of the following command.
./configure --enable-mpi
Thank you very much for your help.

[configure_enable_mpi_output.txt](https://github.com/stephaneguindon/phyml/files/51825/configure_enable_mpi_output.txt)

**Comment by ademcan** [comment]
Hi Stephane, 

Do you have any idea about the reason of the error ?
I didn't manage to get it running, although libtools is installed properly in the system.
It would be really helpful if I can use the version of PhyML supporting multiple threads.
Thank you.

**Comment by stephaneguindon** [comment]
Sorry. I completely forgot to look into this. It looks like libtool is not executed here. Which version of the code are you using here? Also, I assume you used the following command: './configure --enable-mpi' for the configuration, is that right?

**Comment by ademcan** [comment]
No problem :) Yes, I have tried './configure --enable-mpi'.

I tried again with the master branch, I am attaching the output of the command : ./configure --enable-mpi

In addition, I got the following errors now:
sed: can't read ./ltmain.sh: No such file or directory
sed: can't read libtoolT: No such file or directory
[configure_enable_mpi_output.txt](https://github.com/stephaneguindon/phyml/files/68436/configure_enable_mpi_output.txt)

Thanks.

**Comment by stephaneguindon** [comment]
What does 'sh ./autogen.sh;' give?

**Comment by ademcan** [comment]
Here is the output of 'sh ./autogen.sh'

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /software/bin/autoconf --force
configure.ac:69: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /software/bin/autoconf failed with exit status: 1

It seems that libtool is again the issue.

**Comment by stephaneguindon** [comment]
If you're running on OSX, try replacing libtoolize by glibtoolize in autogen.sh. Otherwise, please let me know which OS you're on.

**Comment by ademcan** [comment]
The machine where I want to install PhyML is running on Scientific Linux release 6.7, based on RedHat.

**Comment by stephaneguindon** [comment]
Then it looks like libtool is not properly installed on that machine I guess... Have you tried 'yum install build-essential libtool' ?

**Comment by ademcan** [comment]
Ok, thank you, I will then need to see with our sysadmin as it is asking for root permissions.
Thank you for your help, I will let you know if I managed to get it working.

**Comment by ademcan** [comment]
Is there a way to have a binary of PhyML supporting multi-threading ? Would that work ?

**Comment by stephaneguindon** [comment]
Hi,
I've just updated the 3.2 release by adding binaries for
MPI (and Windows). You might want to give it a go:
https://github.com/stephaneguindon/phyml/releases
Regards,
-Stephane-

**Comment by ademcan** [comment]
Hi, thanks a lot for your help, I really appreciate it.
However, I cannot download the phyml-mpi.binary. It opens an XML file and says 
<Message>The specified key does not exist.</Message> in this file.
Is that normal ?

**Comment by stephaneguindon** [comment]
It should work better now. Please try again.

**Comment by ademcan** [comment]
I can download the binary now, and it seems to run, but I am having another issue.
When I run ./phyml-mpi (or mpirun ./phyml-mpi) just for a test, I get the following error:
./phyml-mpi: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./phyml-mpi)
I guess, I cannot do much more before talking to our sysadmin. I will let you know when I manage to solve this issue... Thank you

**Comment by ademcan** [comment]
Hi Stephane,
Just a quick update to close the issue. I managed to run the phyml-mpi binary using the following command (for 8 threads):
mpirun -n 8 /software/lib64/ld-2.19.90.so phyml-mpi {+ additional parameters}
I needed to use a specific version of libc, and now it works. Thank you very much for your help.

**Comment by yushuqiang** [comment]
> Hi, thank you for this very helpful tool.
> 
> I am trying to compile Phyml from the sources to generate and use the phyml-mpi version.
> When I run the "make" command, it ends up with the following error :
> 
> make[2]: LIBTOOL@: Command not found
> make[2]: *** [phyml-mpi] Error 127
> make[2]: Leaving directory `/home/[USERNAME]/bin/phyml/src' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory`/home/[USERNAME]/bin/phyml'
> make: *** [all] Error 2
> 
> Althought libtools is correctly installed in the machine.
> Do you know how one could solve this issue ? Otherwise, isn't it possible to also provide the phyml-mpi binary in the github repository ?
> Thank you.

Hi,Mr Ademacan,can you tell me how to resolve the question?

**Comment by yushuqiang** [comment]
make[2]: LIBTOOL@: Command not found.



when I am compiling syslog-ng/lib/ivykis。

**Comment by stephaneguindon** [comment]
Can you please describe the version and compilation options you used here?
