### ISSUE TITLE
Unexpected number of bootstrap replicates

### ISSUE THREAD

**Issue by Ivan-Pchelin** [stephaneguindon/phyml#183]
Dear Stephane,

I tried PhyML version 3.3.3:3.3.20211231-1 on Ubuntu 22.04.2. The CPU has 6 physical cores and 12 threads. The problem is that the "-c" option does not work. Every time the program runs the analysis on 6 CPUs and calculates 102 bootstrap replicates instead of 100.

Best wishes,
Ivan

**Comment by Ivan-Pchelin** [comment]
The computer was tested for the ability to use a defined number of threads, up to 12, with vConTACT2 0.11.3.

**Comment by stephaneguindon** [comment]
> Dear Stephane,
> 
> I tried PhyML version 3.3.3:3.3.20211231-1 on Ubuntu 22.04.2. The CPU has 6 physical cores and 12 threads. The problem is that the "-c" option does not work. Every time the program runs the analysis on 6 CPUs and calculates 102 bootstrap replicates instead of 100.
> 
> Best wishes, Ivan

This is the behaviour expected according to our implementation. Indeed, the actual number of bootstrap replicates is the first multiple of the number of CPU cores that is bigger or equal to that asked by the user. Is it an issue?

**Comment by Ivan-Pchelin** [comment]
> @Ivan-Pchelin i can not install mpi version, any help?

Do you work with Linux? If so, do you have the packages autoconf automake and pkg-config installed? What is your precise problem? Actually, the manual seems to be very good.

**Comment by stephaneguindon** [comment]
On Mac with autotools and open-mpi (or mpich) installed, the following should work (this is pretty much the set of instructions already given in the README file):
git clone git@github.com:stephaneguindon/phyml.git; 
cd phyml/;
sh ./autogen.sh;
./configure --enable-phyml-mpi;
make;

**Comment by stephaneguindon** [comment]
> @stephaneguindon Dear Stephane, thank you for your reply. It may not be a big issue. But probably it is an inconvenience. It adds an extra thing to understand and deal with. I believe not all users have to know everything about the software.

I agree this is not ideal. However, I could not find any good reason why someone would not want to obtain a slightly larger number of bootstrap replicates for exactly the same time of computation. I should probably amend the manual in order to explain this though.

**Comment by Ivan-Pchelin** [comment]
> > @stephaneguindon Dear Stephane, thank you for your reply. It may not be a big issue. But probably it is an inconvenience. It adds an extra thing to understand and deal with. I believe not all users have to know everything about the software.
> 
> I agree this is not ideal. However, I could not find any good reason why someone would not want to obtain a slightly larger number of bootstrap replicates for exactly the same time of computation. I should probably amend the manual in order to explain this though.

The reason is in the need to disclose the number of performed bootstrap replicates. There would be an immediate question why there were say 102 instead of normal 100 replicates. Also, if one rounds the number of replicates, there is also a difficulty.

**Comment by stephaneguindon** [comment]
> @stephaneguindon @Ivan-Pchelin error
> 
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/46078579/260673517-60d65e97-142a-47f3-ad58-8c43540fb68c.png">

You need to install open-mpi or mpich on your computer.

**Comment by stephaneguindon** [comment]
> > > @stephaneguindon Dear Stephane, thank you for your reply. It may not be a big issue. But probably it is an inconvenience. It adds an extra thing to understand and deal with. I believe not all users have to know everything about the software.
> > 
> > 
> > I agree this is not ideal. However, I could not find any good reason why someone would not want to obtain a slightly larger number of bootstrap replicates for exactly the same time of computation. I should probably amend the manual in order to explain this though.
> 
> The reason is in the need to disclose the number of performed bootstrap replicates. There would be an immediate question why there were say 102 instead of normal 100 replicates. If one rounds the number of replicates, there is also a difficulty. Also, if I usually take 75% bootstrap as a reliability threshold, what should I think when get 75 out of 102? It adds unnecessary complexity.

Agreed. I'll amend the code accordingly.

**Comment by stephaneguindon** [comment]
brew install openmpi

**Comment by stephaneguindon** [comment]
> > > @stephaneguindon Dear Stephane, thank you for your reply. It may not be a big issue. But probably it is an inconvenience. It adds an extra thing to understand and deal with. I believe not all users have to know everything about the software.
> > 
> > 
> > I agree this is not ideal. However, I could not find any good reason why someone would not want to obtain a slightly larger number of bootstrap replicates for exactly the same time of computation. I should probably amend the manual in order to explain this though.
> 
> The reason is in the need to disclose the number of performed bootstrap replicates. There would be an immediate question why there were say 102 instead of normal 100 replicates. If one rounds the number of replicates, there is also a difficulty. Also, if I usually take 75% bootstrap as a reliability threshold, what should I think when get 75 out of 102? It adds unnecessary complexity.

**Comment by stephaneguindon** [comment]
Fixed in #187
