### ISSUE TITLE
 One or more missing sequences in block 1.

### ISSUE THREAD

**Issue by smoothyly** [stephaneguindon/phyml#188]
Dear stephaneguindon,
  I tried to use PhyML to estimation my tree,but it always get an error:
`. One or more missing sequences in block 1.

. Type enter to exit.
`
My code is :
`phyml -i OG0007266.new.phy -d aa -b 1000 -m LG -f m -v e -a e -o tlr`
and my file is: 
[OG0007266.new.phy.txt](https://github.com/stephaneguindon/phyml/files/13815488/OG0007266.new.phy.txt)
Any pointers or guidance you can provide will be greatly appreciated.

**Comment by timoabe** [comment]
> Dear stephaneguindon, I tried to use PhyML to estimation my tree,but it always get an error: `. One or more missing sequences in block 1.
> 
> . Type enter to exit. `My code is :`phyml -i OG0007266.new.phy -d aa -b 1000 -m LG -f m -v e -a e -o tlr` and my file is: [OG0007266.new.phy.txt](https://github.com/stephaneguindon/phyml/files/13815488/OG0007266.new.phy.txt) Any pointers or guidance you can provide will be greatly appreciated.

Try to delete the spaces in the description, separating the two numbers in the first line with tabs.

**Comment by stephaneguindon** [comment]
Here is a properly formatted version of the alignment : [OG0007266.new.phy.txt](https://github.com/stephaneguindon/phyml/files/13903157/OG0007266.new.phy.txt)
