### ISSUE TITLE
Output filenames incoherence

### ISSUE THREAD

**Issue by RomaricGuillier** [stephaneguindon/phyml#20]
Hello,

It seems that there is an incoherence in the way the output filenames are generated depending on how the software is used.

In the interactive interface: https://github.com/stephaneguindon/phyml/blob/master/src/interface.c#L133 
the ".txt" suffix is added
while in the command line interface: https://github.com/stephaneguindon/phyml/blob/master/src/cl.c#L1429 it is not.

The manual seems to indicate that the version without the extension is the right one ?

Cheers

**Comment by stephaneguindon** [comment]
Indeed. Thanks for pointing this out.
Regards,
-Stephane-
