### ISSUE TITLE
can't read ./ltmain.sh

### ISSUE THREAD

**Issue by chaby** [stephaneguindon/phyml#23]
Hi,

i just perform ./configure and i have the following lines at the end :(
```
sed: can't read ./ltmain.sh: No such file or directory
sed: can't read libtoolT: No such file or directory
```
I'm definitely missed something, any idea?

**Comment by stephaneguindon** [comment]
Please try sh ./autogen.sh before ./configure.
Regards,
-Stephane-

**Comment by chaby** [comment]
This working \o/
thanks a lot
