### ISSUE TITLE
Error while compiling time.c

### ISSUE THREAD

**Issue by chaby** [stephaneguindon/phyml#24]
Sorry for the new issue,
i have done 
./autogen.sh
./configure
make
i have this error :
`libtool: link: gcc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phyml main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o  -lm
times.o: In function `TIMES_Randomize_Tree_With_Time_Constraints':
times.c:(.text+0x61b1): undefined reference to `DATE_Assign_Primary_Calibration'
times.c:(.text+0x61b9): undefined reference to `DATE_Update_T_Prior_MinMax'
times.c:(.text+0x61c1): undefined reference to `DATE_Check_Calibration_Constraints'
times.c:(.text+0x61cf): undefined reference to `DATE_Check_Time_Constraints'
collect2: error: ld returned 1 exit status
`

in think date.o is missing, i had #include "date.h" inside time.c, but i think something expected in the Makefile...

**Comment by stephaneguindon** [comment]
No worries.
The problem should be fixed now. It had to do with Makefile.am.
Regards,
-Stephane-

**Comment by chaby** [comment]
it's working thanks
