### ISSUE TITLE
Error compiling with --enable-mpi

### ISSUE THREAD

**Issue by bioinf-ice** [stephaneguindon/phyml#25]
I also have got some error while compiling with mpi enabled.

I did:

    ./autogen.sh
    ./configure --enable-mpi
    make

Error message:

/bin/bash ../libtool  --tag=CC   --mode=link mpicc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phyml-mpi main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o mpi_boot.o -lm -lm 
libtool: link: mpicc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phyml-mpi main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o mpi_boot.o  -lm
times.o: In function `TIMES_Randomize_Tree_With_Time_Constraints':
times.c:(.text+0x61be): undefined reference to `DATE_Assign_Primary_Calibration'
times.c:(.text+0x61c6): undefined reference to `DATE_Update_T_Prior_MinMax'
times.c:(.text+0x61ce): undefined reference to `DATE_Check_Calibration_Constraints'
times.c:(.text+0x61dc): undefined reference to `DATE_Check_Time_Constraints'
collect2: error: ld returned 1 exit status
Makefile:1721: recipe for target 'phyml-mpi' failed
make[2]: *** [phyml-mpi] Error 1

Do you know how this can be fixed?

Thanks

**Comment by stephaneguindon** [comment]
I've just fixed that (same issue at that that affected phyml a couple of 
days ago). Please  update and try again.
Regards,
-Stephane-

**Comment by bioinf-ice** [comment]
Thanks for helping out! Everything works well now.

BTW: same error appears while using:

    ./configure --enable-phytime
