### ISSUE TITLE
Problem with phytime compilation

### ISSUE THREAD

**Issue by chodarq** [stephaneguindon/phyml#26]
Hi,

I succesfully install phyml (and phyml-mpi and phyml-beagle) from the v3.2 source. However, phytime give me the follow error. Any idea of what happend?
Thanks,
Christian.

/bin/bash ../libtool  --tag=CC   --mode=link gcc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o xml.o phyrex.o -lm -lm 
libtool: link: gcc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o xml.o phyrex.o  -lm
phyrex.o: In function `PHYREX_MCMC':
phyrex.c:(.text+0xcac4): undefined reference to`MCMC_PHYREX_Mu'
phyrex.c:(.text+0xcae4): undefined reference to `MCMC_PHYREX_Lbda'
phyrex.c:(.text+0xcb04): undefined reference to`MCMC_PHYREX_Simulate_Backward'
phyrex.c:(.text+0xcb24): undefined reference to `MCMC_PHYREX_Scale_Times'
phyrex.c:(.text+0xcb44): undefined reference to`MCMC_PHYREX_Prune_Regraft'
phyrex.c:(.text+0xcb64): undefined reference to `MCMC_PHYREX_Swap_Disk'
phyrex.c:(.text+0xcb84): undefined reference to`MCMC_PHYREX_Move_Disk_Updown'
phyrex.c:(.text+0xcba4): undefined reference to `MCMC_PHYREX_Indel_Hit'
phyrex.c:(.text+0xcbc4): undefined reference to`MCMC_PHYREX_Indel_Disk'
phyrex.c:(.text+0xcbe4): undefined reference to `MCMC_PHYREX_Radius'
phyrex.c:(.text+0xcc24): undefined reference to`MCMC_PHYREX_Indel_Hit_Serial'
phyrex.c:(.text+0xcc44): undefined reference to `MCMC_PHYREX_Indel_Disk_Serial'
phyrex.c:(.text+0xcc64): undefined reference to`MCMC_PHYREX_Disk_Given_Ldsk'
phyrex.c:(.text+0xcc84): undefined reference to `MCMC_PHYREX_Ldsk_Given_Disk'
phyrex.c:(.text+0xcca4): undefined reference to`MCMC_PHYREX_Ldsk_And_Disk'
phyrex.c:(.text+0xccc4): undefined reference to `MCMC_PHYREX_Ldsk_Multi'
phyrex.c:(.text+0xcce4): undefined reference to`MCMC_PHYREX_Disk_Multi'
phyrex.c:(.text+0xcd04): undefined reference to `MCMC_PHYREX_Lbda_Times'
phyrex.c:(.text+0xcd24): undefined reference to`MCMC_PHYREX_Lineage_Traj'
phyrex.c:(.text+0xcd44): undefined reference to `MCMC_PHYREX_Simulate_Backward_Plus'
collect2: error: ld returned 1 exit status

**Comment by stephaneguindon** [comment]
Later releases of the package fix this issue.
