### ISSUE TITLE
option 

### ISSUE THREAD

**Issue by evrycollin** [stephaneguindon/phyml#27]
Hello Stephane,

According to the last documentation, 
we've tried to use the new **--print_json_trace** option introduced in PhyML v3.2.0.

This option seams to be not recognized.
We tried with the executable availble for download
We tried with a build of last sources on Fedora 23

**Comment by stephaneguindon** [comment]
Hi Evry,
This option was introduced after the 3.2.0 release. You need to clone 
the latest version of the sources on Github to access it.
Hope this helps,
-Stephane-

**Comment by Fennryr** [comment]
Hello,

the code was compiled on fedora 23 :
```[root@localhost phyml]# cat /proc/version
Linux version 4.2.3-300.fc23.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 5.1.1 20150618 (Red Hat 5.1.1-4) (GCC) ) #1 SMP Mon Oct 5 15:42:54 UTC 201```

the latest commit is this one : 
```
[root@localhost phyml]# git log -1

commit 97cfc935fbc42dcad2a32bfca2fc3f5ea85a2b5a
Author: stephaneguindon <stephane.guindon@gmail.com>
Date:   Wed Apr 13 20:13:35 2016 +0200
    improved sanity checks for partitioned/mixture models
```

The installed version of phyML is : 
```
[root@localhost phyml]# src/phyml --version
. command-line: src/phyml --version 
. This is PhyML version 3.2.20160420.
```

Using the following command line is OK : 
```
[root@localhost phyml]# phyml/src/phyml --input test.txt
```

But this one is not :  
```
[root@localhost phyml]# phyml/src/phyml --input test.txt --print_json_trace
. command-line: phyml/src/phyml --input test.txt --print_json_trace 
phyml/src/phyml: unrecognized option '--print_json_trace'
```

To compile I used the following commands : 
```
./autogen.sh
./configure
make clean
make V=0
```

Thanks 
                         --Benoît

**Comment by stephaneguindon** [comment]
Sorry, the option name is '--json_trace' instead of 
'--print_json_trace'. Will fix the document shortly.
Regards,
-Stephane-
