### ISSUE TITLE
Ancestral state marginal probabilities greater than 1

### ISSUE THREAD

**Issue by dltheobald** [stephaneguindon/phyml#28]
Hi,

Using PhyML 3.2.20160428, in the *_phyml_ancestral_seq output file, I am getting lots of marginal state probabilities greater than one.  Used this command:

phyml -i my.phy -d aa -m LG -f e -v 0 -c 12 -a e -s NNI -o tlr -b 0 --freerates --no_memory_check --ancestral

**Comment by dltheobald** [comment]
Here are associated files for the problem.
[dlt.tar.zip](https://github.com/stephaneguindon/phyml/files/258930/dlt.tar.zip)

**Comment by dltheobald** [comment]
Also, I just noticed that apparently the branch lengths given at the top of *_phyml_ancestral_seq do not match the branchlengths reported in the output ML tree.

**Comment by stephaneguindon** [comment]
Thanks for all that. I'll take a close look at it shortly.
-Stephane-

**Comment by stephaneguindon** [comment]
Hi Douglas,
The problem showed up when using the freerate model for ancestral sequence reconstruction. I've fixed it now. Please feel free to pull the master branch.
Regards,
-Stephane-
