### ISSUE TITLE
the --append option

### ISSUE THREAD

**Issue by maxbiostat** [stephaneguindon/phyml#32]
Was the --append option removed? If so, is there any way I can easily put it back? (I'm comfortable with forking and doing the patching myself).

Thanks in advance,

Luiz

**Comment by stephaneguindon** [comment]
Hi Luiz,
I just switched this option back on.
Regards,
-Stephane-

**Comment by maxbiostat** [comment]
Thanks a bunch, @stephaneguindon!

Best,

Luiz
