### ISSUE TITLE
undefined reference to `Free_Cseq'

### ISSUE THREAD

**Issue by smoretti** [stephaneguindon/phyml#34]
Hi

I try to compile phyml 3.2.20160530 on Linux x86_64, gcc 4.9.1 (openMPI 1.8.1) but it fails:

```
sh ./autogen.sh
/configure --prefix=<...> --enable-phyml --enable-phytime
make
```

/bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o date.o xml.o -lm -lm -ldl
libtool: link: gcc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o date.o xml.o  -lm -ldl
times.o: In function `TIMES_main':
times.c:(.text+0x4032): undefined reference to`Free_Cseq'
collect2: error: ld returned 1 exit status

with MPI enabled, same kind of issue:
/bin/sh ../libtool  --tag=CC   --mode=link mpicc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o date.o xml.o -lm -lm 
libtool: link: mpicc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phytime main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o times.o m4.o draw.o rates.o mcmc.o stats.o mg.o tiporder.o io.o make.o mixt.o init.o nexus.o date.o xml.o  -lm
utilities.o: In function `Bootstrap_From_String':
utilities.c:(.text+0x2c4d1): undefined reference to`Bootstrap_MPI'
times.o: In function `TIMES_main':
times.c:(.text+0x407a): undefined reference to`Free_Cseq'
collect2: error: ld returned 1 exit status

How to solve this?
Regards

**Comment by terrycojones** [comment]
@smoretti See https://github.com/stephaneguindon/phyml/pull/45

The tiny fix there should allow you to compile the program (works for me). If the fix is wrong, you might get a core dump. In that case you could (for now) comment out the call to `Free_Cseq` and run `make`. That would be *deliberately* creating a memory leak, in order to get the program to run.  The best solution will of course be to have the source patched correctly & to install from that. The two things I've just suggested are only temporary measures!

**Comment by terrycojones** [comment]
@smoretti The fix just got merged. So you can ignore my comments above and try building from the latest (i.e., do a git clone & follow the instructions at the bottom of the `README`).

**Comment by smoretti** [comment]
Thanks, phyml, phytime and phyml-mpi compile properly now.
Just another issue with phyrex (see #50)
