### ISSUE TITLE
Does not build with libhmsbeagle

### ISSUE THREAD

**Issue by tillea** [stephaneguindon/phyml#35]
Hi,

may be this is related to issue #12. If I try to build Debian packages from the latest release 3.2.20160530 I get:

...
gcc  -I. -I..   -D_FORTIFY_SOURCE=2  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized  -I/usr/include/libhmsbeagle-1  -lhmsbeagle -ldl   -c -o utilities.o utilities.c
utilities.c: In function ‘Swap_Partial_Lk’:
utilities.c:6233:7: error: ‘temp’ undeclared (first use in this function)
       temp             = b->p_lk_left_idx;
       ^
utilities.c:6233:7: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1836: recipe for target 'utilities.o' failed
...

I checked the diff of utilities.c but did not found any relevant change regarding the temp variable.  I suspect a connection to libhmsbeagle since temp is only used in
# ifdef BEAGLE

enclosed parts of the code.

The issue appears with a Git clone from libhmsbeagle from 2015-06-09 as well as 2016-05-25 (I wished they would use properly versioned releases.

Kind regards

```
    Andreas.
```

**Comment by glque22** [comment]
Hi, 

Has a fix been found for this? I'm still encountering it when compiling v. 3.3.20170530 and a clone from the github code made on Oct. 19, 2017.

Regards,

Gerard

**Comment by stephaneguindon** [comment]
I'm sorry I can't be of much help here. Did you try to contact the people
from
beagle?
Regards,
-Stephane-

2017-10-21 6:57 GMT+02:00 glque22 <notifications@github.com>:

**Comment by glque22** [comment]
Hi,

Thanks for your reply; I'll try to ask the people from beagle about it.

For what its worth, I managed to compile phyml-beagle using phyml version 3.2.0 and beagle release 2_1_2; however, it crashes immediately upon launching bootstrap analysis and the terminal gives no reason for it.

Regards,
Gerard

**Comment by stephaneguindon** [comment]
Thanks Gerard. Also, please note that PhyML* now uses Intel intrinsics. You
should see a substantial increase in speed compared to older releases. It
might not be as fast as the GPU-enabled version "a la" BEAGLE, but you
might be happy enough with it!
Regards,
-Stephane-
* the cloned version from github

2017-10-23 19:49 GMT+02:00 glque22 <notifications@github.com>:

**Comment by glque22** [comment]
Hi,

Thanks for notifying and accomodating me. I haven't actually tried the vanilla version of Phyml on Linux (I've been using it on Windows 7 and 10; now I am running Linux Mint v.18.2). 

I tried it just now using a clone from github, and I cannot seem to define nucleotide frequencies on the Phylip interface. I get a seg fault after setting the model to "custom" with Optimise equilibrium frequencies to "no". When I set Optimise to yes, I am able to set model to "custom" and define my own substitution rates, but when I type "e" to define nucleotide frequences, I once more get a seg fault (and the option "e" does not appear on the menu, I only know it from the manual).

Using the command line version, I am able to define my own nucleotide freq, but then I cannot define substitution rates.

I have tried cloning again from github and re-making phyml, but the seg fault persists.

Regards,
Gerard

PS. Should I maybe have opened a new thread? I am sorry for hijacking this one, but I wished to reply to your comment.

**Comment by tillea** [comment]
Hi,

On Tue, Oct 24, 2017 at 08:02:22AM -0700, glque22 wrote:
> now I am running Linux Mint v.18.2). 

Did you tried the Debian packaged version which should run on Mint?

If yes, could you please provide the data set and the exact command line
you are calling to enable me reproducing the segfault on a Debian
system?

**Comment by glque22** [comment]
Hi,

I have not yet tried the Debian packaged versions, but I shall do so soon and get back to you with my results.

The segfault only arises using the Phylip interface; the command line interface does not seem to have a problem (my only issue with the command line is the inability to set my own substitution rates). In a Phylip interface, Substitution model sub-menu, I cannot set the model to custom if 'optimise equilibrium frequencies' is set to no; doing so causes a segfault. I have tried 2 or 3 data sets and the error still occurs.

I'll download the debian packages and see what I get. Thank you.

Regards,
Gerard

**Comment by glque22** [comment]
Hi,

I have tried using the a packaged version of phyml v3.3.2.0+dfsg -7 found on the software installer that comes with Linux Mint. It seems to be identical to the one found on the Debian package database.

I'm happy to say I no longer encounter the segfault error when using the Phylip interface. I wonder what causes this to occur when I use a clone or download a release from github?

Many thanks to both of you for your responses and help.

Regards,
Gerard

**Comment by tillea** [comment]
On Tue, Oct 24, 2017 at 06:39:20PM +0000, glque22 wrote:
> I'm happy to say I no longer encounter the segfault error when using the Phylip interface. I wonder what causes this to occur when I use a clone or download a release from github?
I have no direct answer for you.  There is the urban myth that Mint (and Ubuntu) are "easy to use" (whatever this actually means).  I will not comment on this advertising clause.  However, if you are a bioinformatican working with several bioinformatics software you are probably well served by Debian since there is a team behind this software that cares about this stuff.  May be you want to have a look at https://blends.debian.org/med/tasks/bio and if you find the software you need marked "green" you might like to reconsider your decision.  Feel free to contact debian-med@lists.debian.org if you have more detailed questions.
Andreas.

**Comment by glque22** [comment]
I must admit, the reason I chose Linux Mint was because its said to be easy to use. True enough, it isn't that different compared to Windows, in that I could expect it to (mostly) "just work". Apart from occasional bugs when compiling programs and initial problems with the Grub bootloader, it works fine (and I quite like the look and feel of the Cinnamon desktop). 

However, I do intend to transition to a different version of Linux, once I have more experience with the OS and the time to download and install a new one. Debian looks attractive, given its support for various bioinformatics software and I shall definitely consider trying it out. Thanks for your time and support.

Regards,
Gerard
