### ISSUE TITLE
Regression in output file naming, missing .txt extension

### ISSUE THREAD

**Issue by peterjc** [stephaneguindon/phyml#39]
There has been a regression in the automatic output file naming which broke one of the Biopython PhyML wrapper tests - see https://github.com/biopython/biopython/issues/919

Historical behavour as per PhyML 3.1 from the http://www.atgc-montpellier.fr/phyml/download.php website:

```
$ curl -L -O https://raw.githubusercontent.com/biopython/biopython/master/Tests/Phylip/interlaced2.phy
$ curl -L -O http://www.atgc-montpellier.fr/download/binaries/phyml/PhyML-3.1.zip
$ unzip PhyML-3.1.zip
$ rm -rf  interlaced2.phy_*
$  ./PhyML-3.1/PhyML-3.1_linux64 -i interlaced2.phy -d aa ; echo "Return code $?"
...
Return code 0
$ ls -1 interlaced2.phy*
interlaced2.phy
interlaced2.phy_phyml_stats.txt
interlaced2.phy_phyml_tree.txt
```

Using PhyML from GitHub as of 03a2597eeeaf4877cb25cf76f2fc814c2ba8e2c7 built from source and installed under $PATH,

```
$ rm -rf  interlaced2.phy_*
$ phyml -i interlaced2.phy -d aa ; echo "Return code $?"
...
Return code 0
$ ls -1 interlaced2.phy*
interlaced2.phy
interlaced2.phy_phyml_stats
interlaced2.phy_phyml_tree
```

Notice the ``.txt`` extension is missing, appending only ``_phyml_stats`` and ``_phyml_tree`` to the input filename.

This puzzles me as from reading the code ``interface.c`` e.g. https://github.com/stephaneguindon/phyml/blob/03a2597eeeaf4877cb25cf76f2fc814c2ba8e2c7/src/interface.c#L274 still seems to use the input filename plus ``_phyml_tree.txt``

```
  strcpy(io->out_tree_file,io->in_align_file);
  strcat(io->out_tree_file,"_phyml_tree.txt");
```

**Comment by stephaneguindon** [comment]
I can't remember why I did that... I just pushed a new commit that fixes this throughout.
Regards,
-Stephane-

**Comment by peterjc** [comment]
Thanks - 43c4e2817d1d690a1421fe3b01ff50b136dc7046
