### ISSUE TITLE
Changelog version numbers and dates do not match phyml

### ISSUE THREAD

**Issue by peterjc** [stephaneguindon/phyml#40]
File https://github.com/stephaneguindon/phyml/blob/master/ChangeLog was commited in 2014 and not changed since. It lists changes to versions 4.1 and 5.0 from 1999 to 2000.

The current PhyML is version 3.3, so this ``ChangeLog`` does not make sense.

**Comment by peterjc** [comment]
It looks like you removed the ``ChangeLog`` as part of 43c4e2817d1d690a1421fe3b01ff50b136dc7046

**Comment by stephaneguindon** [comment]
Indeed. The content of that file was not relevant to PhyML.

Regards,

-Stephane-

**Comment by peterjc** [comment]
Thanks for clarifying this, closing issue :)
