### ISSUE TITLE
Outgroup in bootstrap analysis

### ISSUE THREAD

**Issue by isana18** [stephaneguindon/phyml#42]
Hi 
I am using the latest version of phyML - phyml-3.2.20160530, and when I run the bootstrap analysis, the outgroup that I specified do not appear as such in the generated trees.

**Comment by stephaneguindon** [comment]
Hi there,

Do you mean the outgroup has an incorrect position in the ML tree (which 
would be an issue) or in the trees estimated from every bootstrap 
replicate (which wouldn't be an issue in my opinion)?

Regards,

-Stephane-

**Comment by isana18** [comment]
Hi, thanks for the response.
First, the ML tree does not seem to be rooted:

(44*:1.89104210,(31:0.11328452,((2:0.13019657,(32:0.00000000,(18:0.00029243,27:0.00128261)3:0.00010831)5:0.13746015)3:0.02154710,(4:0.13842957,(43:0.12241495,(36:0.00055226,37:0.00028450)5:0.13549395)1:0.02020444)1:0.00861578)2:0.02355513)5:0.11111786,(7:0.08240078,(40:0.09705255,(29:0.10013697,((((3:0.06777164,41:0.06040587)5:0.04388047,(21:0.10046038,38:0.08349534)1:0.01012665)0:0.00455182,((((17:0.04262885,(16:0.00103572,0:0.00047296)5:0.04044617)5:0.04749967,(1:0.09245731,(8:0.01540993,(14:0.00050288,(15:0.00050291,(19:0.00107663,(9:0.00000001,10:0.00000001)5:0.00061090)5:0.00010755)4:0.00000017)5:0.01032888)5:0.07275482)5:0.00944830)1:0.01194691,((11:0.10558387,(5:0.06322062,39:0.07703640)5:0.03225599)2:0.00947802,(13:0.08834801,33:0.10719584)4:0.01279698)0:0.00430275)0:0.00487401,(((35:0.02274112,34:0.02142994)5:0.07527325,(26:0.09019409,12:0.10065434)3:0.00999921)1:0.00586501,(42:0.10295800,(25:0.11210444,(22:0.09337807,24:0.08058190)5:0.01526800)3:0.00593894)3:0.00501743)0:0.00598552)0:0.00388658)0:0.00400141,((6:0.00017508,(23:0.00010776,20:0.00025168)4:0.00011323)5:0.09606643,(28:0.00970764,30:0.01077114)5:0.08987523)4:0.01177910)0:0.00505419)2:0.00933664)3:0.02677463)5:0.15066526);

and in the bootstrap trees the 44* (outgroup) is not outgrouped either.
When I run older version of phyML (PhyML-3.1_linux64), the outgroup was always outgrouped in the trees, but the bootstrap values did not match the bootstrapped trees, this is why I moved to a newer version.

Thanks

**Comment by stephaneguindon** [comment]
Ok. I'll look into it.

Not sure what you mean by ``the bootstrap values did not match the 
bootstrapped trees". In PhyML, the estimated tree is the ML one and we

score each edge in this tree by counting how many bootstrap trees 
display that branch. It is different from displaying the bootstrap 
values on

a tree given by the consensus of all bootstrap trees.

Regards,

-Stephane-

**Comment by isana18** [comment]
thank you for checking the issue.

But what if the consensus of the bootstrapped trees looks exactly like the ML tree, than the values should be the same?

**Comment by stephaneguindon** [comment]
On 30/09/2016 18:24, isana18 wrote:

> thank you for checking the issue.
>
> But what if the consensus of the bootstrapped trees looks exactly like 
> the ML tree, than the values should be the same?
>

Indeed. I'd be interested if you can provide me with an example where you
noticed a discrepancy.
Regards,
-Stephane-

**Comment by isana18** [comment]
Ok, so just to make sure, it is not a bug in the new version, that when an outgroup is specified, and the bootstrap option is used, the outgroup can be anywhere in the bootstrapped trees?

thanks

**Comment by stephaneguindon** [comment]
If by outgroup you mean only one taxa, then I think it is fine that it 
does not show as outgroup

in the bootstrap trees.

Regards,

-Stephane-
