### ISSUE TITLE
configure: error: cannot find macro directory `m4'

### ISSUE THREAD

**Issue by abrozzi** [stephaneguindon/phyml#43]
Hi,

I get this error while trying to configure:

```
[brozzal1]$ uname -a
Linux 2.6.18-194.17.4.el5 #1 SMP Mon Oct 25 15:50:53 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux
[brozzal1]$ arch
x86_64
```
```
[brozzal1]$ ./configure --prefix=/home/brozzal1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
configure: error: cannot find macro directory `m4'
```

FYI before I did in my home:

```
tar -xvzf m4-1.4.17.tar.gz
mv m4-1.4.17 m4
cd m4
./configure --prefix=/home/brozzal1
make
make install
```

Thank you

**Comment by stephaneguindon** [comment]
Try ./autogen.sh first and then ./configure.
Regards,
-Stephane-

**Comment by abrozzi** [comment]
Hi,
thank you. I did it but the result is the same:

```
[brozzal1 phyml]$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
```

```
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
configure: error: cannot find macro directory `m4'
```
May I missing something about where m4 should be installed or where is goes to search it?

**Comment by stephaneguindon** [comment]
Try '|./configure ||--prefix=/home/brozzal1|'|instead of './configure' 
since you installed|
|m4 locally. If it still doesn't work, I guess you should try to install 
m4 globally... |
Sorry I can't be of much assistance here...
|Regards,|
|-Stephane-|

||

||

**Comment by whokan** [comment]
I couldn't compile the code either and tried many many solutions from pulling new m4 libraries to reinstalling glibc.

What finally solved it for me was just executing make on the sms.zip files that's available. It has a version of phyml that would compile on my system.
