### ISSUE TITLE
Numerical precision alert

### ISSUE THREAD

**Issue by terrycojones** [stephaneguindon/phyml#48]
I've just git cloned the phyml repo and built both `phyml` and `phyml-mpi` following the instructions in the `README`. This is on x86_64, Redhat Scientific Linux release 7.2 (Nitrogen). When I run either phymly or the MPI version:

```sh
$ phyml -i input.fasta -m 012212 -f e -v e -c 4 -a e -b 10
```
I get an almost-immediate error:

```
. First round of optimization...
== fact_sum_scale: 1049
== pi: 0.219838
== pi 0: 0.228185
== pi 1: 0.269256
== pi 2: 0.219838
== pi 3: 0.282721
== Numerical precision issue alert.
== File lk.c at line 1472 (function '(null)')

== fact_sum_scale: 1048
== pi: 0.219838
== pi 0: 0.228185
== pi 1: 0.269256
== pi 2: 0.219838
== pi 3: 0.282721
== Numerical precision issue alert.
== File lk.c at line 1472 (function '(null)')

== l=0.000824346 lk=0.219073 dlk=INF d2lk=INF
== Err. in file 'lk.c' (line 833)
```

and the process exits with status `1`.

If I run the pre-compiled binary from `http://www.atgc-montpellier.fr/download/binaries/phyml/PhyML-3.1.zip`  the error does not happen.

I'd like to use the MPI version, but there is no pre-compiled binary for it.

Thanks!

**Comment by stephaneguindon** [comment]
Yep, I'll need a bit of time to look into this one carefully. Will get back to you asap.

**Comment by terrycojones** [comment]
Thanks. I'm happy to help with debugging if you like.

**Comment by stephaneguindon** [comment]
Feel free to have a look but I guess this one is a tad tricky...

**Comment by stephaneguindon** [comment]
This issue might be fixed in the latest commit. Feel free to have a look and let me know how it goes.
