### ISSUE TITLE
Input format is reported as interleaved when it's not

### ISSUE THREAD

**Issue by terrycojones** [stephaneguindon/phyml#49]
When I provide a regular FASTA file to phyml using `-i file.fasta` the initial overview printed by the program includes the line

```
                . Sequence format:                               interleaved
```

which seems to be wrong. It would be good to fix this because it makes the user wonder if it's just an error in what's being printed in the summary or if phyml really did try to read the FASTA in some interleaved way.

**Comment by stephaneguindon** [comment]
interleaved is the default format in PhyML so I am not sure I understand what is wrong here... Ideally the program would bail out before printing this sort of information but I don't think it is too much of an issue that it does.

**Comment by terrycojones** [comment]
OK, I was confused here - sorry!  Closing.
