### ISSUE TITLE
error on make after ./configure --enable-mpi

### ISSUE THREAD

**Issue by thirtysix** [stephaneguindon/phyml#5]
Hello again,
Here is an error I am getting after an mpi enable config.
Thanks for any help.
"""
...
mpicc  -I. -I..     -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized  -MT mpi_boot.o -MD -MP -MF .deps/mpi_boot.Tpo -c -o mpi_boot.o mpi_boot.c
mpi_boot.c: In function ‘Bootstrap_MPI’:
mpi_boot.c:210:7: warning: passing argument 2 of ‘Connect_CSeqs_To_Nodes’ from incompatible pointer type [enabled by default]
       Connect_CSeqs_To_Nodes(boot_data,boot_tree);
       ^
In file included from mpi_boot.h:19:0,
                 from mpi_boot.c:13:
utilities.h:1970:6: note: expected ‘struct option *’ but argument is of type ‘struct t_tree *’
 void Connect_CSeqs_To_Nodes(calign *cdata, option *io, t_tree *tree);
      ^
mpi_boot.c:210:7: error: too few arguments to function ‘Connect_CSeqs_To_Nodes’
       Connect_CSeqs_To_Nodes(boot_data,boot_tree);
       ^
In file included from mpi_boot.h:19:0,
                 from mpi_boot.c:13:
utilities.h:1970:6: note: declared here
 void Connect_CSeqs_To_Nodes(calign *cdata, option *io, t_tree *tree);
      ^
make[2]: *** [mpi_boot.o] Error 1
make[2]: Leaving directory `home/.../bin/phyml-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/.../bin/phyml-master'
"""

**Comment by stephaneguindon** [comment]
Indeed. It's fixed now. Thank you.

**Comment by thirtysix** [comment]
Worked without a hitch thanks!
