### ISSUE TITLE
Compile error in Perl_xs_apiversion_bootcheck

### ISSUE THREAD

**Issue by aWormGuy** [stephaneguindon/phyml#53]
Dear Stephane,
I am trying to install phyml on a linux cluster. I downloaded the zip file via "Clone or download" --> "Download ZIP" option, moved the file to my cluster head node, unzipped and cd to phyml-master directory. When I run:
`sh ./autogen.sh` 
I get the following error:
`/usr/bin/perl: symbol lookup error: /share/pkg/perl/5.18.1/lib/5.18.1/x86_64-linux-thread-multi/auto/Fcntl/Fcntl.so: undefined symbol: Perl_xs_apiversion_bootcheck`

I have two versions of perl on my cluster (1) `perl/5.10.0` installed by default on my head node, (2) But I load and use `/share/pkg/perl/5.18.1` from our cluster library (so that I can install perl modules locally). 
To me the error seems to be that the Build script is picking the wrong version of perl. I usually can fix this by replacing 
`#! /usr/bin/perl` 
with 
`#! /usr/bin/env perl` 
in Build.PL etc., but here I am unable to figure out where to specify the perl version to use. 
Could you please help me solve this?
Thanks a lot,
-Amit.

**Comment by stephaneguindon** [comment]
Hi Amit,
It looks like this problem has more to do with the install of the machine you're using than PhyML. I'm closing this issue.
Regards,
-Stephane-
