### ISSUE TITLE
Providing a Custom substitution model creates malformed characters in the output

### ISSUE THREAD

**Issue by seb-biomatters** [stephaneguindon/phyml#54]
Hi, we ran into a bug from some sources we compiled on 2016-05-30 and recently released to our userbase as part of our Geneious PHYML plugin. It seems that when you specify a custom substitution model when invoking from the command line, the output file xxxx_phyml_stats has some malformed characters where it's meant to list the custom model number. See attached output file, that came from the command:

{...}/phyml_linux_64 --boot_progress_every 1 --{...}/PHYML --datatype nt --sequential --multiple 1 --bootstrap 100 --model 012210 -t e --pinv 0.846 --nclasses 1 --alpha e -o tlr --search NNI

[PHYML_phyml_stats.txt](https://github.com/stephaneguindon/phyml/files/837052/PHYML_phyml_stats.txt)

I've tried it with a few different alignments and different substitution model numbers, and it's malformed in each case. We can workaround the bug for now, but I think the problem is somewhere in the output producing code.

**Comment by stephaneguindon** [comment]
More recent versions of PhyML fix this bug.
