### ISSUE TITLE
Outdated web site

### ISSUE THREAD

**Issue by arvestad** [stephaneguindon/phyml#55]
Hi, 
A collaborator is confused by the versioning of PhyML, since http://www.atgc-montpellier.fr/phyml/ is showing other information than what github says. The latest version is said to be 3.1 and the source code is available "on request".

**Comment by peterjc** [comment]
As part of this, http://www.atgc-montpellier.fr/phyml/faq.php says:

> Where can I get the sources for PhyML ?
PhyML was developped under the GNU Public Licence (GPL). The sources are freely available. However, we like to know what people to do with our code. Hence, to get the files, send an e-mail to Stéphane Guindon with just a few words about the reasons why you need the sources.

**Comment by stephaneguindon** [comment]
We've just updated that page. Thanks.
