### ISSUE TITLE
Versioning inconsistencies again

### ISSUE THREAD

**Issue by protist** [stephaneguindon/phyml#57]
As per issue #31, the versioning is still incorrect. I just rebuilt and installed the most recent release, `v3.3.20170530`, and it's still reporting the build date instead.
```
$ phyml-mpi --version

. Command line: phyml-mpi --version 

. This is PhyML version 3.3.20170531.
```

**Comment by stephaneguindon** [comment]
The versioning is correct as long as one avoids running sh ./autogen.sh for
the compilation of a release, which, I guess, is what you did here (see
README file)
Regards,
-Stephane-

2017-05-31 7:28 GMT+02:00 protist <notifications@github.com>:

**Comment by protist** [comment]
Do you mean manually running `sh ./autogen.sh`? AFAIK I'm not running it. I just tried again, following the README instructions precisely, and I can still replicate the issue.

```
$ wget https://github.com/stephaneguindon/phyml/archive/v3.3.20170530.tar.gz
$ tar -xzf v3.3.20170530.tar.gz
$ cd phyml-3.3.20170530
$ ./configure --enable-phyml
$ make
$ src/phyml --version 

. Command line: src/phyml --version 

. This is PhyML version 3.3.20170601.
```

I also got a few warnings during `make`, including below. I'm happy to post the full output if it's helpful.
```
aclocal-1.15: warning: couldn't open directory 'm4': No such file or directory
 cd . && /bin/sh /tmp/phyml-3.3.20170530/missing automake-1.15 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /tmp/phyml-3.3.20170530/missing autoconf
/bin/sh ./config.status --recheck
`

**Comment by stephaneguindon** [comment]
You're right. I've pushed a commit that fixes this issue (the release
version is now hard-coded). It'll be available in the next release.
Regards,
-Stephane-

2017-06-01 5:00 GMT+02:00 protist <notifications@github.com>:

**Comment by protist** [comment]
Thank you for fixing that! Cheers.
