### ISSUE TITLE
Trace encoding

### ISSUE THREAD

**Issue by marcoooo** [stephaneguindon/phyml#60]
Phyml current trace and stderr are set with non-ascii caracters 'bullet-point', is it possible to remove them from traces ? Just to be sure file could be retrieve without decode / encode problems ?
use '-' instead ?
Many thanxs.
Marc

**Comment by stephaneguindon** [comment]
Ok, will do.
Regards,
-Stephane-

2017-09-21 13:06 GMT+02:00 Marc Chakiachvili <notifications@github.com>:
