### ISSUE TITLE
Err in file utilities.c at line 6331 (function "temp")

### ISSUE THREAD

**Issue by glque22** [stephaneguindon/phyml#63]
Hi, 

I've been trying to build the beagle-enabled version of phyml; I cloned directly from GitHub. I've been getting an error during compilation after launching the command make: the function "temp" seems to be undefined in the file utilities.c at line 6331 
 
$ make
make  all-recursive
make[1]: Entering directory '/home/gerard/Desktop/phymlmaster'
Making all in src
make[2]: Entering directory '/home/gerard/Desktop/phymlmaster/src'

.: Building [phyml-beagle]. Version 3.3.20170530 :.

gcc  -I. -I..     -std=c99 -O2 -fomit-frame-pointer -funroll-loops -Wall -Winline -march=native -I/usr/local/include/libhmsbeagle-1 -L/usr/local/lib -lhmsbeagle -ldl -lstdc++ -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc  -I. -I..     -std=c99 -O2 -fomit-frame-pointer -funroll-loops -Wall -Winline -march=native -I/usr/local/include/libhmsbeagle-1 -L/usr/local/lib -lhmsbeagle -ldl -lstdc++ -MT utilities.o -MD -MP -MF .deps/utilities.Tpo -c -o utilities.o utilities.c
utilities.c: In function ‘Swap_Partial_Lk’:
utilities.c:6331:7: error: ‘temp’ undeclared (first use in this function)
       temp             = b->p_lk_left_idx;
       ^
utilities.c:6331:7: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1710: recipe for target 'utilities.o' failed
make[2]: *** [utilities.o] Error 1
make[2]: Leaving directory '/home/gerard/Desktop/phymlmaster/src'
Makefile:370: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/gerard/Desktop/phymlmaster'
Makefile:311: recipe for target 'all' failed
make: *** [all] Error 2

Is there any way I can fix this?

Thanks,
Gerard

PS. This may be related to issue #35 and issue #12.

**Comment by stephaneguindon** [comment]
The BEAGLE features in PhyML are no longer maintained I'm afraid... You may need to contact the developers of this library to see if they can help you out.
