### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hutaotsmc** [stephaneguindon/phyml#64]
Hello,
I'm exiting with this error when running with bootstraps, but not when running without it.
I'm appending the output infomation in support.
Cheers

. Command line: phyml -i primatesNT.phy -d nt -b 10

                                 ..........................
 ooooooooooooooooooooooooooooo        CURRENT SETTINGS        ooooooooooooooooooooooooooooooooooo
                                 ..........................

        ? Sequence filename:                             primatesNT.phy
        ? Data type:                                     dna
        ? Alphabet size:                                 4
        ? Sequence format:                               interleaved
        ? Number of data sets:                           1
        ? Nb of bootstrapped data sets:                  10
        ? Compute approximate likelihood ratio test:     no
        ? Model name:                                    HKY85
        ? Ts/tv ratio:                                   estimated
        ? Proportion of invariable sites:                0.000000
        ? Number of subst. rate catgs:                   4
        ? Gamma distribution parameter:                  estimated
        ? 'Middle' of each rate class:                   mean
        ? Nucleotide equilibrium frequencies:            empirical
        ? Optimise tree topology:                        yes
        ? Tree topology search:                          NNIs
        ? Starting tree:                                 BioNJ
        ? Add random input tree:                         no
        ? Optimise branch lengths:                       yes
        ? Optimise substitution model parameters:        yes
        ? Run ID:                                        none
        ? Random seed:                                   1515225441
        ? Subtree patterns aliasing:                     no
        ? Version:                                       3.3.20180106
        ? Byte alignment:                                32
        ? AVX enabled:                                   yes
        ? SSE enabled:                                   yes

. 336 patterns found (out of a total of 1500 sites).

. 986 sites without polymorphism (65.73%).

. Computing pairwise distances...

. Building BioNJ tree...

. This analysis requires at least 4 MB of memory space.

. Score of initial tree:     -6417.69

. Building a list of starting trees (NNI search)...

         ╭─────────────────────────╮
         │   0          -6416.10   │ .
         ├─────────────────────────┤
         │   1          -6416.10   │ .
         ├─────────────────────────┤
         │   2          -6416.10   │
         ├─────────────────────────┤
         │   3          -6416.10   │ .
         ├─────────────────────────┤
         │   4          -6416.10   │ .
         ├─────────────────────────┤
         │   5          -6416.10   │
         ├─────────────────────────┤
         │   6          -6416.10   │ .
         ├─────────────────────────┤
         │   7          -6416.10   │
         ├─────────────────────────┤
         │   8          -6416.10   │
         ├─────────────────────────┤
         │   9          -6416.10   │
         ├─────────────────────────┤
         │  10          -6416.10   │ .
         ├─────────────────────────┤
         │  11          -6416.10   │
         ├─────────────────────────┤
         │  12          -6416.10   │
         ├─────────────────────────┤
         │  13          -6416.10   │
         ├─────────────────────────┤
         │  14          -6416.10   │
         ╰─────────────────────────╯

. Fast optimisation of the best trees (SPR search)...

         ╭─────────────────────────╮
         │   1          -6416.07   │ .
         ╰─────────────────────────╯

. Thorough optimisation of the best trees (SPR search)...

         ╭─────────────────────────╮
         │   1          -6416.07   │ .
         ├─────────────────────────┤
         │   2          -6416.07   │ .
         ╰─────────────────────────╯

. Final optimisation steps...

. Log likelihood of the current tree: -6416.071827.

. Launch bootstrap analysis on the most likely tree...

. Non parametric bootstrap analysis

  [Segmentation fault

**Comment by stephaneguindon** [comment]
My bad... I've introduced the bug very recently. It should be fixed now.
