### ISSUE TITLE
Versioning inconsistencies III

### ISSUE THREAD

**Issue by protist** [stephaneguindon/phyml#65]
As per issue #31 and #57, this new release still incorrectly reports its version. I built `v3.3.20180129`, and it's reporting `3.3.20180130`.

```
$ wget https://github.com/stephaneguindon/phyml/archive/v3.3.20180129.tar.gz
$ tar -xzf v3.3.20180129.tar.gz
$ cd phyml-3.3.20180129
$ ./configure --enable-phyml
$ make
...
make[2]: Entering directory '/tmp/phyml/phyml-3.3.20180129/src'
...
.: Building [phyml]. Version 3.3.20180130 :.
...
$ src/phyml --version

. Command line: src/phyml --version 

. This is PhyML version 3.3.20180130.
```
N.B. the inconsistencies within the output of `make` as well.

**Comment by stephaneguindon** [comment]
Yes, my bad. I have now hardcoded the version number in configure.ac
to avoid this sort of issue.
Regards,
-Stephane-

**Comment by protist** [comment]
Thank you for the quick fix. It's working fine now. Cheers.
