### ISSUE TITLE
Print more digits of log likelihood if given a --verbose option.

### ISSUE THREAD

**Issue by bredelings** [stephaneguindon/phyml#68]
Hi,

I think it would be useful to allow showing more digits of the log-likelihood if the user requests it.

One approach would be to add a --verbose option.  This could be used project-wide to enable increased logging without recompiling.  Then we could print more digits of the log likelihood if --verbose is given.

-BenRI

**Comment by stephaneguindon** [comment]
PhyML now prints out the final log-likelihood using the maximum precision available (which depends on the machine you're using).
