### ISSUE TITLE
Request for a --likelihood-only option.

### ISSUE THREAD

**Issue by bredelings** [stephaneguindon/phyml#69]
Hi,

Some users would benefit from being able to evaluate the likelihood at the initial parameter settings, without doing any optimization.

Currently, I am adding `--leave_duplicates -b 0 -o n` in order to get this effect.  However, it would be nice to 
* document how to evaluate the likelihood only (if it is not documented)
* add an explicit option that will have the right effect as PhyML changes over time (if you know what I mean)

-BenRI

**Comment by stephaneguindon** [comment]
You actually don't need to use the --leave_duplicates option. Just '-b 0 and -o n' will return the log-likelihood score without performing any optimization.
