### ISSUE TITLE
Allow setting GTR parameters from the command line.

### ISSUE THREAD

**Issue by bredelings** [stephaneguindon/phyml#70]
Hi,

In order to evaluate likelihoods from the command line, it would be useful to be able to specify all model parameters from the command line.  The GTR parameters are perhaps the prime example of parameters that cannot be specified on the command line.

Some other ML software (e.g. RAxML and IQ-TREE) seem to work roughly like this:
* GTR{a,b,c,d,e,f}+G4{alpha}+I{pInv}

-BenRI

**Comment by stephaneguindon** [comment]
This option is available in the latest official release.
