### ISSUE TITLE
Crash of Phytime

### ISSUE THREAD

**Issue by jblamyatifremer** [stephaneguindon/phyml#73]
Dear PhyML creators, 

I download the lastest git-hub version and compile-it without any (visible) error on Ubuntu 14.04. When I launch this command:

phytime --input "$phylip" --datatype nt --inputtree "$TREE" --model GTR --nclasses 4 --calibration "$CALIBRATION"

The beginning of the computation seems ok... but suddently it crashes. 
I copy/paste the output

------------------------------------------------------------------------------------
. Seed: 1533713952

. Pid: 6081

. Compressing sequences...

. 8001 patterns found (out of a total of 343330 sites). 

. 187608 sites without polymorphism (54.64%).

. Reading tree...

. Reading prior on node ages.

. [  1]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "LI"
. Lower bound set to:      -40.000000 time units.
. Upper bound set to:      -40.000000 time units.
. .......................................................................

. [  2]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "MV"
. Lower bound set to:      -40.000000 time units.
. Upper bound set to:      -40.000000 time units.
. .......................................................................

. [  3]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NZ"
. Lower bound set to:      -40.000000 time units.
. Upper bound set to:      -40.000000 time units.
. .......................................................................

. [  4]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NZW16"
. Lower bound set to:      -39.000000 time units.
. Upper bound set to:      -39.000000 time units.
. .......................................................................

. [  5]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NZW17"
. Lower bound set to:      -39.000000 time units.
. Upper bound set to:      -39.000000 time units.
. .......................................................................

. [  6]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NZW18"
. Lower bound set to:      -39.000000 time units.
. Upper bound set to:      -39.000000 time units.
. .......................................................................

. [  7]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "PR"
. Lower bound set to:      -42.000000 time units.
. Upper bound set to:      -42.000000 time units.
. .......................................................................

. [  8]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "SW6"
. Lower bound set to:      -38.000000 time units.
. Upper bound set to:      -38.000000 time units.
. .......................................................................

. [  9]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NC_011646_1"
. Lower bound set to:      -47.000000 time units.
. Upper bound set to:      -37.000000 time units.
. .......................................................................

. [ 10]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "KU096999_1"
. Lower bound set to:      -42.000000 time units.
. Upper bound set to:      -32.000000 time units.
. .......................................................................

. [ 11]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NC_018874_1"
. Lower bound set to:      -45.000000 time units.
. Upper bound set to:      -45.000000 time units.
. .......................................................................

. [ 12]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "GQ153938_1"
. Lower bound set to:      -43.000000 time units.
. Upper bound set to:      -43.000000 time units.
. .......................................................................

. [ 13]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NC_019491"
. Lower bound set to:      -69.000000 time units.
. Upper bound set to:      -58.000000 time units.
. .......................................................................

. [ 14]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "MF509813_1"
. Lower bound set to:      -58.000000 time units.
. Upper bound set to:      -38.000000 time units.
. .......................................................................

. [ 15]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "NC_005881_2"
. Lower bound set to:      -58.000000 time units.
. Upper bound set to:      -51.000000 time units.
. .......................................................................

. [ 16]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "KY242785_1"
. Lower bound set to:      -42.000000 time units.
. Upper bound set to:      -36.000000 time units.
. .......................................................................

. [ 17]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "KY271630_1"
. Lower bound set to:      -42.000000 time units.
. Upper bound set to:      -36.000000 time units.
. .......................................................................

. [ 18]..................................................................
. Node   32 matches the clade referred to with the following taxon names:
. - "@root@"
. Lower bound set to:     -120.000000 time units.
. Upper bound set to:     -100.000000 time units.
. .......................................................................
. Read prior information on 18 clades.

. (    0 sec) [  -1044741.3094] [Branch lengths     ]
. (    4 sec) [  -1019544.0818] [GTR parameters     ]
. (    4 sec) [  -1019291.9153] [Alpha              ][  1.175938]
. (    5 sec) [  -1019291.9153] [Branch lengths     ]
. (   10 sec) [  -1012842.7077] [GTR parameters     ]
. (   10 sec) [  -1012155.2741] [Alpha              ][  1.643140]
. (   10 sec) [  -1012155.2741] [Branch lengths     ]
. (   14 sec) [  -1011931.7277] [GTR parameters     ]
. (   14 sec) [  -1011900.9736] [Alpha              ][  1.782089]
. (   14 sec) [  -1011900.9736] [Branch lengths     ]
. (   18 sec) [  -1011809.8317] [GTR parameters     ]
. (   18 sec) [  -1011790.6479] [Alpha              ][  1.907194]
. (   18 sec) [  -1011790.6479] [Branch lengths     ]
. (   21 sec) [  -1011727.8328] [GTR parameters     ]
. (   21 sec) [  -1011703.4003] [Alpha              ][  2.071653]
. (   22 sec) [  -1011703.4003] [Branch lengths     ]
. (   25 sec) [  -1011651.4691] [GTR parameters     ]
. (   25 sec) [  -1011629.2521] [Alpha              ][  2.254018]
. (   25 sec) [  -1011629.2521] [Branch lengths     ]
. (   28 sec) [  -1011585.0618] [GTR parameters     ]
. (   29 sec) [  -1011565.4775] [Alpha              ][  2.454445]
. (   29 sec) [  -1011565.4775] [Branch lengths     ]
. (   32 sec) [  -1011530.4563] [GTR parameters     ]
. (   32 sec) [  -1011512.8670] [Alpha              ][  2.676912]
. (   32 sec) [  -1011512.8670] [Branch lengths     ]
. (   35 sec) [  -1011484.0308] [GTR parameters     ]
. (   36 sec) [  -1011469.7222] [Alpha              ][  2.912668]
. (   36 sec) [  -1011469.7222] [Branch lengths     ]
. (   39 sec) [  -1011447.3102] [GTR parameters     ]
. (   39 sec) [  -1011435.2416] [Alpha              ][  3.165932]
. (   39 sec) [  -1011435.2416] [Branch lengths     ]
. (   42 sec) [  -1011417.7577] [GTR parameters     ]
. (   42 sec) [  -1011408.4772] [Alpha              ][  3.425199]
. (   42 sec) [  -1011408.4772] [Branch lengths     ]
. (   45 sec) [  -1011395.2249] [GTR parameters     ]
. (   46 sec) [  -1011387.8248] [Alpha              ][  3.693160]
. (   46 sec) [  -1011387.8248] [Branch lengths     ]
. (   49 sec) [  -1011377.9395] [GTR parameters     ]
. (   49 sec) [  -1011372.4468] [Alpha              ][  3.958814]
. (   49 sec) [  -1011372.4468] [Branch lengths     ]
. (   52 sec) [  -1011365.1154] [GTR parameters     ]
. (   52 sec) [  -1011360.9003] [Alpha              ][  4.223781]
. (   52 sec) [  -1011360.9003] [Branch lengths     ]
. (   55 sec) [  -1011355.6218] [GTR parameters     ]
. (   56 sec) [  -1011352.5906] [Alpha              ][  4.473406]
. (   56 sec) [  -1011352.5906] [Branch lengths     ]
. (   59 sec) [  -1011348.8279] [GTR parameters     ]
. (   59 sec) [  -1011346.5539] [Alpha              ][  4.715510]
. (   59 sec) [  -1011346.5539] [Branch lengths     ]
. (   62 sec) [  -1011343.8958] [GTR parameters     ]
. (   62 sec) [  -1011342.3028] [Alpha              ][  4.938259]
. (   63 sec) [  -1011342.3028] [Branch lengths     ]
. (   65 sec) [  -1011340.4013] [GTR parameters     ]
. (   66 sec) [  -1011339.2392] [Alpha              ][  5.144655]
. (   66 sec) [  -1011339.2392] [Branch lengths     ]
. (   69 sec) [  -1011337.9418] [GTR parameters     ]
. (   69 sec) [  -1011337.1308] [Alpha              ][  5.329810]
. (   69 sec) [  -1011337.1308] [Branch lengths     ]
. (   72 sec) [  -1011336.2191] [GTR parameters     ]
. (   72 sec) [  -1011335.6398] [Alpha              ][  5.496215]
. (   72 sec) [  -1011335.6398] [Branch lengths     ]
. (   75 sec) [  -1011335.0267] [GTR parameters     ]
. (   76 sec) [  -1011334.6287] [Alpha              ][  5.641633]
. (   76 sec) [  -1011334.6287] [Branch lengths     ]
. (   79 sec) [  -1011334.1989] [GTR parameters     ]
. (   79 sec) [  -1011333.9161] [Alpha              ][  5.771884]
. (   79 sec) [  -1011333.9161] [Branch lengths     ]
. (   82 sec) [  -1011333.6221] [GTR parameters     ]
. (   82 sec) [  -1011333.4317] [Alpha              ][  5.881567]
. (   82 sec) [  -1011333.4317] [Branch lengths     ]
. (   85 sec) [  -1011333.2307] [GTR parameters     ]
. (   85 sec) [  -1011333.0963] [Alpha              ][  5.975380]
. (   86 sec) [  -1011333.0963] [Branch lengths     ]
. (   88 sec) [  -1011332.9728] [GTR parameters     ]
. (   88 sec) [  -1011332.8804] [Alpha              ][  6.059773]
. (   89 sec) [  -1011332.8804] [Branch lengths     ]
. (   91 sec) [  -1011332.7771] [GTR parameters     ]
. (   91 sec) [  -1011332.7021] [Alpha              ][  6.137368]
. (   92 sec) [  -1011332.7021] [Branch lengths     ]
. (   94 sec) [  -1011332.6401] [GTR parameters     ]
. (   95 sec) [  -1011332.5962] [Alpha              ][  6.196917]
. (   95 sec) [  -1011332.5962] [Branch lengths     ]
. (   97 sec) [  -1011332.5539] [GTR parameters     ]
. (   98 sec) [  -1011332.5224] [Alpha              ][  6.247505]
. (   98 sec) [  -1011332.5224] [Branch lengths     ]
. (  100 sec) [  -1011332.4964] [GTR parameters     ]
. (  101 sec) [  -1011332.4767] [Alpha              ][  6.287061]
. (  101 sec) [  -1011332.4767] [Branch lengths     ]
. (  103 sec) [  -1011332.4596] [GTR parameters     ]
. (  104 sec) [  -1011332.4460] [Alpha              ][  6.319486]
. (  104 sec) [  -1011332.4460] [Branch lengths     ]
. (  107 sec) [  -1011332.4353] [GTR parameters     ]
. (  107 sec) [  -1011332.4264] [Alpha              ][  6.345002]
. (  107 sec) [  -1011332.4264] [Branch lengths     ]
. (  110 sec) [  -1011332.4195] [GTR parameters     ]
. (  110 sec) [  -1011332.4130] [Alpha              ][  6.366308]
. (  110 sec) [  -1011332.4130] [Branch lengths     ]
. (  113 sec) [  -1011332.4088] [GTR parameters     ]
. (  113 sec) [  -1011332.4043] [Alpha              ][  6.389789]
. (  113 sec) [  -1011332.4043] [Branch lengths     ]
. (  116 sec) [  -1011332.3994] [GTR parameters     ]
. (  116 sec) [  -1011332.3967] [Alpha              ][  6.408384]
. (  116 sec) [  -1011332.3967] [Branch lengths     ]
. (  119 sec) [  -1011332.3936] [GTR parameters     ]
. (  119 sec) [  -1011332.3918] [Alpha              ][  6.423922]
. (  119 sec) [  -1011332.3918] [Branch lengths     ]
. (  122 sec) [  -1011332.3898] [GTR parameters     ]
. (  122 sec) [  -1011332.3887] [Alpha              ][  6.436776]
. (  122 sec) [  -1011332.3887] [Branch lengths     ]
. (  125 sec) [  -1011332.3874] [GTR parameters     ]
. (  125 sec) [  -1011332.3867] [Alpha              ][  6.443213]
. (  125 sec) [  -1011332.3867] [Branch lengths     ]
. (  128 sec) [  -1011332.3863] [GTR parameters     ]
. (  128 sec) [  -1011332.3858] [Alpha              ][  6.449656]
. (  129 sec) [  -1011332.3858] [GTR parameters     ]
. (  129 sec) [  -1011332.3858] [Alpha              ][  6.449656]

. Computing Hessian...

. p(data|model) [exact ] ~ -1011332.39
. p(data|model) [approx] ~ 248.87
. Selected model 'gbs'*** Error in `phytime': malloc(): memory corruption: 0x00000000020a1a10 ***
/media/jean-baptiste/ABIETRY/OshV1/04_phylogenetic_tree/03_script/MakePhylogenyPhyTime.bash: line 58:  6081 Aborted                 phytime --input "$phylip" --datatype nt --inputtree "$TREE" --model GTR --nclasses 4 --calibration "$CALIBRATION"

I am working on 46 cores machine with 128 Go ram. I welcome any ideas and/or suggestion. 

JB

**Comment by stephaneguindon** [comment]
I may have replied to you on another channel (I hope so...). I will look into this asap.
