### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by epruesse** [stephaneguindon/phyml#76]
From the source code and older versions of PhyML I gather that it is licensed under the GPL. The GPL requires that a copy of the license be distributed with the software. The file "COPYING" used to be distributed with PhyML, but appears to be missing in recent releases.

**Comment by stephaneguindon** [comment]
I've added a COPYING file corresponding to the GPL.

**Comment by epruesse** [comment]
@stephaneguindon Thanks!
