### ISSUE TITLE
undefined reference to `MIGREP_Update_Sigsq'

### ISSUE THREAD

**Issue by danillo-alvarenga** [stephaneguindon/phyml#8]
Hey! Compiling the latest version (396:449M - 20150602) in Ubuntu 14.10 with GCC 4.9.1 results in the following error:

.: Building [phyml]. Version 20150602 :.

/bin/bash ../libtool  --tag=CC   --mode=link gcc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phyml main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o -lm -lm 
libtool: link: gcc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phyml main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o  -lm
mcmc.o: In function `MCMC_Copy_To_New_Param_Val':
mcmc.c:(.text+0xa44a): undefined reference to `MIGREP_Update_Sigsq'
collect2: error: ld returned 1 exit status
Makefile:1560: recipe for target 'phyml' failed
make[2]: *** [phyml] Error 1

**Comment by stephaneguindon** [comment]
I just fixed the issue. Please update, re-configure and re-compile.
Regards,
-Stephane-

**Comment by danillo-alvarenga** [comment]
It's working now. Thank you very much! Cheers!
