### ISSUE TITLE
Remove identical sequences

### ISSUE THREAD

**Issue by cynthiawqy** [stephaneguindon/phyml#83]
Hi,
I just want to make a small opinion. If it would be better if phyml doesn't remove same sequences? Otherwise the number of taxa in the output will be different from the number in original dataset. This may cause confusion. Thanks.

**Comment by stephaneguindon** [comment]
PhyML now treats identical sequences in a transparent manner (it removes them in order to speed up the analysis then put them back on the tree at the end of the analysis).
