### ISSUE TITLE
Integrated branch lengths (--il)

### ISSUE THREAD

**Issue by bobkallal** [stephaneguindon/phyml#85]
Hi,

I seem to be having an issue with the integrated branch lengths flag of PhyML. My local cluster has v3.1 and it does not recognized the --il flag. I have a copy of the manual (v3.0) from September 14, 2018 that does include the --il flag. Is the --il function no longer supported in v3.1?

> phyml: unrecognized option '--il'

Thank you!

**Comment by stephaneguindon** [comment]
Hi there,
Sorry for the late reply. The "integrated length" (il) model needs a bit of working on recent versions of PhyML unfortunately. It's best to avoid it for now or use an older release if you need to.
Regards,
-Stephane-

**Comment by bobkallal** [comment]
Thank you for the reply.
