### ISSUE TITLE
phyml execution time

### ISSUE THREAD

**Issue by sghignone** [stephaneguindon/phyml#88]
Dear Stephane,
I am wondering how much I do expect the analysis (dna and GTR) must last with large files, with alignments of more than a thousand sequences. I have just lost an analysis of 7 alignments (launched in parallel) that were up since Nov. 8, and started over again....

thanks 
s.-

**Comment by stephaneguindon** [comment]
I am not sure the code of PhyTime is optimized enough at the moment to deal with such large data sets unfortunately...
