### ISSUE TITLE
No SH-like values

### ISSUE THREAD

**Issue by BiodivGenomic** [stephaneguindon/phyml#89]
Dear Stephane,
I run phyml tree since quite a long time, and I had almost no issue until the last versions...
I cannot get anymore the SH-like values on my result trees... PhyML is taking a long time (>12h for 15 plastomes sequences) to calculate the SH values, but then the tree has no node values.

I tried it on several computers, rebuilding from sources, nothing changed...
Is there a solution to get SH-like values ?
Thanks a lot in advance, Damien

**Comment by stephaneguindon** [comment]
This issue is fixed in the latest official release.
