### ISSUE TITLE
phyml -h

### ISSUE THREAD

**Issue by hedjour** [stephaneguindon/phyml#9]
Hi
In command line phyml -h with the last commit give a "Erreur de segmentation (core dumped)"
after print the start of help :

>-m (or --model) model
>		model : substitution model name.
>		- Nucleotide-based models : HKY85 (default) | JC69 | K80 | F81 | F84 | TN93 | GTR | custom (\*)
>		(\*) : for the custom option, a string of six digits identifies the model. For instance, 000000
>		 corresponds to F81 (or JC69 provided the distribution of nucleotide frequencies is uniform).
>		 012345 corresponds to GTR. This option can be used for encoding any model that is a nested within GTR.
>
>Erreur de segmentation (core dumped)

**Comment by stephaneguindon** [comment]
I couldn't reproduce this issue (on a linux machine)... Can you be more specific?

**Comment by hedjour** [comment]
My machine is a Ubuntu 14.04.2.
I have run in my phyml git repository
>./configure
>make clean
>make

These commands give :
>make  all-recursive
>make[1]: entrant dans le répertoire «[...]/phyml »
>Making all in src
>make[2]: entrant dans le répertoire « [...]/phyml/src »
>.: Building [phyml]. Version 20150603 :.
>[...]
> No warning no errors occured
>/bin/bash ../libtool  --tag=CC   --mode=link gcc  -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized    -o phyml main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o -lm -lm 
libtool: link: gcc -Wall -O2 -msse -fomit-frame-pointer -funroll-loops -Wempty-body -Wuninitialized -o phyml main.o utilities.o optimiz.o lk.o bionj.o models.o free.o help.o simu.o eigen.o pars.o alrt.o interface.o cl.o spr.o draw.o stats.o rates.o mcmc.o times.o tiporder.o mg.o m4.o io.o make.o nexus.o init.o xml.o mixt.o  -lm

>Done.
>make[2]: quittant le répertoire « [...]/phyml/src »
>make[2]: entrant dans le répertoire « [...]/phyml »
>make[2]: quittant le répertoire « [...]/phyml »
>make[1]: quittant le répertoire « [...]/phyml »

Then  **./src/phyml -h** : 

>. command-line: ./src/phyml -h NAME
>	- PhyML 20150603 - 
>
>	''A simple, fast, and accurate algorithm to estimate
>	large phylogenies by maximum likelihood''
>
>	Stephane Guindon and Olivier Gascuel,
>	Systematic Biology 52(5):696-704, 2003.
>
>	Please cite this paper if you use this software in your publications.

>SYNOPSIS:
>
>	phyml [command args]
>
>	All the options below are optional (except '-i' if you want to use the command-line interface).


>Command options:

>	-i (or --input) seq_file_name
		seq_file_name is the name of the nucleotide or amino-acid sequence file in PHYLIP format.

[...]
>	-m (or --model) model
>		model : substitution model name.
>		- Nucleotide-based models : HKY85 (default) | JC69 | K80 | F81 | F84 | TN93 | GTR | >custom (*)
>		(*) : for the custom option, a string of six digits identifies the model. For instance, 000000
>		 corresponds to F81 (or JC69 provided the distribution of nucleotide frequencies is uniform).
>		 012345 corresponds to GTR. This option can be used for encoding any model that is a nested within GTR.
>
>Erreur de segmentation (core dumped)

What other information can be more usefull ?

**Comment by hedjour** [comment]
Solution cette erreur proviens du manques d'une ligne 
LINE,FLAT à la ligne 151 du fichier help.c
