### ISSUE TITLE
./configure  Error

### ISSUE THREAD

**Issue by jhh130910** [stephaneguindon/phyml#96]
./configure: line 5057: syntax error near unexpected token `BEAGLE,'

./configure: line 5057: `  PKG_CHECK_MODULES(BEAGLE, hmsbeagle-1)'

**Comment by stephaneguindon** [comment]
Not sure what version you are using here, which OS, etc...

**Comment by PhanNgan** [comment]
I got the same issue. I use the newest version of phyml-3.3.20190321. 
I use Ubuntu 18.04.2 LTS
Below are my command for installation:
wget https://github.com/stephaneguindon/phyml/tree/v3.3.20190321
cd phyml-3.3.20190321/
sh ./autogen.sh;
./configure --enable-phyml; make;
then error:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking for log in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking for pdflatex... no
checking for latex... no
configure: WARNING: Documentation will not be built!
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for pow... yes
checking for rint... yes
checking for sqrt... yes
checking for strchr... yes
checking for strstr... yes
./configure: line 5069: syntax error near unexpected token `BEAGLE,'
./configure: line 5069: `  PKG_CHECK_MODULES(BEAGLE, hmsbeagle-1)'
make: *** No targets specified and no makefile found.  Stop.
Please help me! Thanks alot!

**Comment by stephaneguindon** [comment]
The command  wget https://github.com/stephaneguindon/phyml/tree/v3.3.20190321
gets you a file, not a directory containing PhyML source files. Are you sure these really are the steps
you followed?

**Comment by PetraGutenbrunner** [comment]
Hi, 
I get the same error as above described when running the code as suggested: sh ./autogen.sh; ./configure --enable-win --enable-phyml; make;

**Comment by stephaneguindon** [comment]
In the file 'configure.ac', can you please try and replace
PKG_CHECK_MODULES(BEAGLE,hmsbeagle-1)
with
PKG_CHECK_MODULES([BEAGLE],[hmsbeagle-1])
and then re-run ./configure; make;

**Comment by PetraGutenbrunner** [comment]
Thank you for your quick reply. Just did what you suggested, unfortunately I still get the error:

./configure: line 5069: syntax error near unexpected token `[BEAGLE],'
./configure: line 5069: `    PKG_CHECK_MODULES([BEAGLE], [hmsbeagle-1])'

I also tried using PKG_CHECK_MODULES(BEAGLE, hmsbeagle-1 >= 1.0.0) and also with [] but same issue

**Comment by stephaneguindon** [comment]
On linux, you need to have the package pkg-config installed. If you're using Ubuntu, you can try the following command: sudo apt-get install pkg-config

Alternatively, you can comment out lines 107-113 in the configure.ac file.

**Comment by PetraGutenbrunner** [comment]
Commenting them out works. But if I do so, will I miss any functionality?

**Comment by stephaneguindon** [comment]
A version of PhyML that uses the BEAGLE library for the calculation of the likelihood can be obtained with ./configure --enable-beagle. This option is no longer available when you comment out the corresponding lines in configure.ac. But if you were not planning on using the BEAGLE-enabled version of PhyML anyway, then you're not missing out on any option.

**Comment by PetraGutenbrunner** [comment]
Ok, thank you
