### ISSUE TITLE
Br_Len_Spline: Assertion `FALSE' failed

### ISSUE THREAD

**Issue by pedro-mb** [stephaneguindon/phyml#97]
Hi, I'm running phyml and phyml-mpi version 3.3.20190321 and on both occasions I got the following error, during boostrap analysis:
phyml version (alignment file 1)

```
nohup phyml -i PSITM.trimal.phy -d aa -m LG -a e -f e -v e -b 100 --run_id PSIboot100BEST.noth > boot100BESTnoth.log.txt &
```

> . Non parametric bootstrap analysis 
> 
>   [....................]   20/ 100
>   [..................
> . iter=   0 u= 5.01358E-15 fu=     -161164 dfu=1.16871E+293 v=     3.85676 fv=     -144221 dfv=    -1.72012 root1=        -NAN root2=        -NAN
> phyml: optimiz.c:2407: Br_Len_Spline: Assertion `FALSE' failed.
> 

or 
phyml-mpi (alignment file 2)

```
nohup mpirun -np 20 -mca btl ^openib phyml-mpi -i einsi2.trimal.phy -d aa -m LG -a e -f e -v 0.0 -b 100 --run_id einsi_e.boot100BEST > boot100BEST.log.txt
```

> . The bootstrap analysis will use 20 CPUs.
>   [phyml-mpi: optimiz.c:2407: Br_Len_Spline: Assertion `FALSE' failed.
> 
> . iter=   0 u= 3.42531E-15 fu=     -158962 dfu=8.09236E+302 v=     3.16195 fv=     -145165 dfv=    -5.55218 root1=        -NAN root2=        -NAN
> 
> 

I'm currently running phyml for alignment file 2 (whitout MPI) and it's almost finishing without any error.  I'm using Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)
Any idea? Thank you in advance

**Comment by stephaneguindon** [comment]
I set the minimum edge length to 1E-15 in the last official release. It turns out that this value is too small and makes the optimization routine prone to numerical precision issues. This was fixed in subsequent commits. Please feel free to clone and give it a go.
