### ISSUE TITLE
Illegal instruction (core dumped) - 3.3.20180621, bioconda installation

### ISSUE THREAD

**Issue by servalli** [stephaneguindon/phyml#99]
Phyml crashes shortly after starting a job.
See https://github.com/bioconda/bioconda-recipes/issues/14613

**Comment by stephaneguindon** [comment]
The version of PhyML obtained through bioconda has just been upgraded. Do you mind updating your conda package of PhyML and trying again?

**Comment by servalli** [comment]
The problem persists after update to 3.3.20190321.

**Comment by stephaneguindon** [comment]
I am not quite sure whether it is problem with PhyML or with the bioconda package. @epruesse might be able to help?

**Comment by epruesse** [comment]
Could be either PhyML or Bioconda (or rather the Conda compiler settings). The last version was compiled with gcc 4.9, the new one with gcc 7, though.

It's good that this is happening on a machine of your own. We saw illegal instructions with `vsearch` as well, but only on Travis on some machines, so it was really hard to track.

@stephaneguindon I assume you have some SSE code / CPU detection in PhyML?

**Comment by epruesse** [comment]
@servalli How good are you at debugging? Does this happen only with the Bioconda package, or also with a locally built version of PhyML?

**Comment by servalli** [comment]
I was wrong, the working version is only the locally built one, the installation from Bioconda crashes also on 18.04, so the issue is definitely on this side.
Sorry for misconception.

**Comment by epruesse** [comment]
Hmm.

**Comment by epruesse** [comment]
When you are in `gdb`, once it ran into the illegal instruction, you should be able to tell GDB to issue a full trace. Either `bt full` or `thread apply bt` should get you a trace that's a little bit longer. If you could post that here, it could help figure out exactly where the instruction is hiding that your CPUs don't have.

**Comment by epruesse** [comment]
(@stephaneguindon The function mentioned in the other issue was `Are_Compatible`, but that doesn't really call any SIMD instructions as far as I can tell. Might be optimization hiding it.)

**Comment by servalli** [comment]
`bt full` output

```
#0  0x00005555555755c0 in Are_Compatible ()
No symbol table info available.
#1  0x000055555557795f in Compact_Data ()
No symbol table info available.
#2  0x000055555555653d in main ()
No symbol table info available.
```

**Comment by epruesse** [comment]
Thanks. That's not much to go by though. @stephaneguindon - ideas?

**Comment by stephaneguindon** [comment]
> @stephaneguindon I assume you have some SSE code / CPU detection in PhyML?
Yes, I do have SSE (and AVX) code. But no CPU detection.

**Comment by epruesse** [comment]
No CPU detection? So PhyML requires a box with AVX? Do you know what the minimum CPU is you expect people to have? @servalli had a Xeon E5 v2, so Ivy Bridge I believe.

**Comment by servalli** [comment]
It is also failing with i5-3470S CPU (on second machine, the one with 18.04)

**Comment by stephaneguindon** [comment]
gcc is using the option -march=native during compilation, which detects whether AVX or SSE or none of them is available.

**Comment by epruesse** [comment]
Ok - culprit located then. I've fixed in the build script by overriding CFLAGS when calling make.

New binaries are available for Linux already - macos is still building. 

Let's hope they didn't get slow. If so, I may have to build for various CPUs and add a bash script that picks the right one.

**Comment by epruesse** [comment]
Thanks everyone!
